/* app-utils.js */

// --- Constants & Data ---
const EXAMPLE_CSV = `"tags","kanji","readings","definition"
"1","出す","だ|す","to take out / to submit"
"1","大人","おとな","adult"
"1","見える","み|える","to be visible"
"1","出る","で|る","to go out / to exit"
"1","小学校","しょうがっこう","elementary school"
"1","天気","てんき","weather"
"1","白い","しろ|い","white"
"1","川","かわ","river"
"1","男の子","おとこのこ","boy"
"1","口","くち","mouth"
"1","見つかる","み|つかる","to be found"
"1","学校","がっこう","school"
"1","大学","だいがく","university"
"1","音","おと","sound"
"1","見せる","み|せる","to show"
"1","左","ひだり","left"
"1","大きい","おお|きい","big"
"1","木","き","tree"
"1","山","やま","mountain"
"1","気","き","spirit / mood"
"1","女の子","おんなのこ","girl"
"1","本","ほん","book"
"1","右","みぎ","right"
"1","小さい","ちい|さい","small"
"1","見る","み|る","to see"
"1","雨","あめ","rain"
"1","休み","やす|み","rest / holiday"
"1","お金","お|かね","money"
"1","入れる","い|れる","to put in"
"1","犬","いぬ","dog"
"1","中学生","ちゅうがくせい","junior high student"
"1","生まれる","う|まれる","to be born"
"1","左右","さゆう","left and right"
"1","入学","にゅうがく","school entrance"
"1","男","おとこ","man"
"1","虫","むし","insect"
"1","土","つち","soil / earth"
"1","学生","がくせい","student"
"1","中学","ちゅうがく","junior high school"
"1","女","おんな","woman"
"1","空気","くうき","air / atmosphere"
"1","早い","はや|い","early / fast"
"1","見つける","み|つける","to find"
"1","町","まち","town"
"1","手","て","hand"
"1","人生","じんせい","life"
"1","花","はな","flower"
"1","上下","じょうげ","up and down"
"1","休む","やす|む","to rest"
"1","男子","だんし","boy / male"
"1","赤ちゃん","あか|ちゃん","baby"
"1","文学","ぶんがく","literature"
"1","中","なか","inside / middle"
"1","上手","じょうず","skillful"
"1","先生","せんせい","teacher"
"1","人口","じんこう","population"
"1","年","とし","year / age"
"1","大学生","だいがくせい","university student"
"1","車","くるま","car"
"1","赤い","あか|い","red"
"1","青","あお","blue"
"1","立つ","た|つ","to stand"
"1","文字","もじ","character / letter"
"1","足","あし","leg / foot"
"1","日本","にほん","Japan"
"1","下さる","くだ|さる","to give (polite)"
"1","上がる","あ|がる","to go up"
"1.1","花だん","か|だん","flower bed"
"1.1","花たば","はな|たば","bouquet"
"1.1","花びら","はな|びら","flower petal"
"1.1","木かげ","こ|かげ","shade of a tree"
"1.1","にわ木","にわ|き","garden tree"
"1.1","木目","もくめ","wood grain"
"1.1","ざっ草","ざっ|そう","weeds"
"1.1","草もち","くさ|もち","rice cake with mugwort"
"1.1","草はら","くさ|はら","grassy field"
"1.1","ちょ金","ちょ|きん","savings"
"1.1","金いろ","きん|いろ","gold color"
"1.1","ほう石","ほう|せき","gem / jewel"
"1.1","じ石","じ|しゃく","magnet"
"1.1","小石","こいし","pebble"
"1.1","赤土","あかつち","red clay / red soil"
"1.1","土足","どそく","with shoes on / muddy feet"
"1.1","ほら貝","ほら|がい","conch shell"
"1.1","まき貝","まき|がい","spiral shell"
"1.1","貝がら","かい|がら","shell"
"1.1","ふじ山","ふじ|さん","Mt. Fuji"
"1.1","山いも","やま|いも","yam"
"1.1","山みち","やま|みち","mountain path"
"1.1","虫かご","むし|かご","insect cage"
"1.1","こん虫","こん|ちゅう","insect"
"1.1","すず虫","すず|むし","bell cricket"
"1.1","川べり","かわ|べり","riverbank"
"1.1","川しも","かわ|しも","downstream"
"1.1","川かみ","かわ|かみ","upstream"
"1.1","日じ","にち|じ","date and time"
"1.1","犬ぞり","いぬ|ぞり","dog sled"
"1.1","白い犬","しろいいぬ","white dog"
"1.1","名犬","めいけん","faithful dog / famous dog"
"1.1","山林","さんりん","mountain forest"
"1.1","まつ林","まつ|ばやし","pine forest"
"1.1","竹林","ちくりん","bamboo grove"
"1.1","まん月","まん|げつ","full moon"
"1.1","月見","つきみ","moon viewing"
"1.1","田うえ","た|うえ","rice planting"
"1.1","水田","すいでん","paddy field"
"1.1","田んぼ","たん|ぼ","rice field"
"1.1","青森","あおもり","Aomori (place)"
"1.1","森林","しんりん","forest"
"1.1","森の中","もりのなか","in the forest"
"1.1","火のこ","ひ|のこ","sparks / fire sparks"
"1.1","火山","かざん","volcano"
"1.1","火じ","か|じ","fire / conflagration"
"1.1","年より","とし|より","elderly person"
"1.1","年上","としうえ","older / senior"
"1.1","竹わ","ちく|わ","chikuwa (fish cake)"
"1.1","竹やぶ","たけ|やぶ","bamboo thicket"
"1.1","竹うま","たけ|うま","stilts"
"1.1","水どう","すい|どう","water supply"
"1.1","水草","みず|くさ","water plant"
"1.1","水玉","みず|たま","polka dot / water drop"
"1.1","き立","き|りつ","stand up"
"1.1","立てる","た|てる","to stand something up"
"1.1","かい力","かい|りき","superhuman strength"
"1.1","学力","がくりょく","academic ability"
"1.1","力もち","ちから|もち","strong person"
"1.1","大へん","たい|へん","difficult / very"
"1.1","大すき","だい|すき","love / like a lot"
"1.1","空ばこ","から|ばこ","empty box"
"1.1","空いろ","そら|いろ","sky blue"
"1.1","休じつ","きゅう|じつ","holiday / day off"
"1.1","休める","やす|める","to rest (something)"
"1.1","口べに","くち|べに","lipstick"
"1.1","口ぶえ","くち|ぶえ","whistle"
"1.1","中にわ","なか|にわ","courtyard"
"1.1","中学校","ちゅうがっこう","middle school"
"1.1","天ごく","てん|ごく","heaven"
"1.1","天の川","あまのがわ","Milky Way"
"1.1","出ぱつ","しゅっ|ぱつ","departure"
"1.1","目てき","もく|てき","purpose / goal"
"1.1","目つき","め|つき","look (in eyes)"
"1.1","目と口","めとくち","eyes and mouth"
"1.1","げん気","げん|き","healthy / energetic"
"1.1","気もち","き|もち","feeling"
"1.1","入り口","いりぐち","entrance"
"1.1","入る","はいる","to enter"
"1.1","はく手","はく|しゅ","applause"
"1.1","手くび","て|くび","wrist"
"1.1","右手","みぎて","right hand"
"1.1","上ぎ","うわ|ぎ","jacket / outerwear"
"1.1","上げる","あ|げる","to raise"
"1.1","木の上","きのうえ","on the tree"
"1.1","雨ぐも","あま|ぐも","rain cloud"
"1.1","雨天","うてん","rainy weather"
"1.1","雨ふり","あめ|ふり","rainfall / rainy"
"1.1","女と男","おんなとおとこ","woman and man"
"1.1","女の人","おんなのひと","woman"
"1.1","女子","じょし","girl / woman"
"1.1","足くび","あし|くび","ankle"
"1.1","足あと","あし|あと","footprint"
"1.1","下校","げこう","coming home from school"
"1.1","下げる","さ|げる","to lower"
"1.1","木の下","きのした","under the tree"
"1.1","夕ぐれ","ゆう|ぐれ","dusk / twilight"
"1.1","夕がた","ゆう|がた","evening"
"1.1","夕日","ゆうひ","setting sun"
"1.1","男の人","おとこのひと","man"
"1.1","目と耳","めとみみ","eyes and ears"
"1.1","耳うち","みみ|うち","whispering in ear"
"1.1","耳たぶ","みみ|たぶ","earlobe"
"1.1","左足","ひだりあし","left foot"
"1.1","左がわ","ひだり|がわ","left side"
"1.1","空白","くうはく","blank space"
"1.1","白い花","しろいはな","white flower"
"1.1","白ぐみ","しろ|ぐみ","white team"
"1.1","子犬","こいぬ","puppy"
"1.1","子ども","こ|ども","child"
"1.1","音いろ","ね|いろ","tone color / timbre"
"1.1","雨の音","あめのおと","sound of rain"
"1.1","音ぷ","おん|ぷ","musical note"
"1.1","右がわ","みぎ|がわ","right side"
"1.1","青空","あおぞら","blue sky"
"1.1","青年","せいねん","youth / young man"
"1.1","青い","あお|い","blue"
"1.1","人げん","にん|げん","human"
"1.1","めい人","めい|じん","master / expert"
"1.1","人ごみ","ひと|ごみ","crowd of people"
"1.1","見学","けんがく","field trip / study"
"1.1","円けい","えん|けい","circular shape"
"1.1","円ばん","えん|ばん","disk"
"1.1","円い","まる|い","round"
"1.1","赤はん","せき|はん","red rice (festive)"
"1.1","赤い車","あかいくるま","red car"
"1.1","早める","はや|める","to hasten"
"1.1","早足","はやあし","quick pace"
"1.1","本名","ほんみょう","real name"
"1.1","名じん","めい|じん","master / expert"
"1.1","名まえ","な|まえ","name"
"1.1","正かい","せい|かい","correct answer"
"1.1","正じき","しょう|じき","honest"
"1.1","正しい","ただ|しい","correct / right"
"1.1","てん字","てん|じ","braille"
"1.1","すう字","すう|じ","number / digit"
"1.1","かん字","かん|じ","kanji characters"
"1.1","こく王","こく|おう","king"
"1.1","王かん","おう|かん","crown"
"1.1","王さま","おう|さま","king"
"1.1","文なし","もん|なし","penniless"
"1.1","文がく","ぶん|がく","literature"
"1.1","さく文","さく|ぶん","composition / essay"
"1.1","玉手ばこ","たまて|ばこ","Pandora's box"
"1.1","玉虫","たまむし","jewel beetle"
"1.1","本とう","ほん|とう","truth / really"
"1.1","本だな","ほん|だな","bookshelf"
"1.1","え本","え|ほん","picture book"
"1.1","きぬ糸","きぬ|いと","silk thread"
"1.1","赤い糸","あかいいと","red thread"
"1.1","白い糸","しろいいと","white thread"
"1.1","学ぶ","まな|ぶ","to learn"
"1.1","小学生","しょうがくせい","elementary student"
"1.1","学年","がくねん","school grade"
"1.1","車りん","しゃ|りん","wheel"
"1.1","でん車","でん|しゃ","train"
"1.1","青い車","あおいくるま","blue car"
"1.1","てん校","てん|こう","changing schools"
"1.1","校てい","こう|てい","schoolyard"
"1.1","山村","さんそん","mountain village"
"1.1","町と村","まちとむら","towns and villages"
"1.1","村の人","むらのひと","villager"
"1.1","足の先","あしのさき","toes / tip of foot"
"1.1","先とう","せん|とう","head / lead"
"1.1","町村","ちょうそん","towns and villages"
"1.1","町の中","まちのなか","in the town"
"1.1","町なみ","まち|なみ","townscape"
"1.1","生もの","なま|もの","raw food"
"1.1","生きる","い|きる","to live"
"1.1","生む","う|む","to give birth"
"2","東","ひがし","East"
"2","地下","ちか","underground/basement"
"2","引っ越す","ひっこ|す","to move (house)"
"2","ボール","ぼーる","ball"
"2","プレゼント","ぷれぜんと","present/gift"
"2","会話","かいわ","conversation"
"2","アルバイト","あるばいと","part-time job"
"2","運転","うんてん","driving"
"2","会場","かいじょう","venue"
"2","散歩","さんぽ","walk/stroll"
"2","入院","にゅういん","hospitalization"
"2","イギリス","いぎりす","UK/Britain"
"2","本当","ほんとう","truth/reality"
"2","スキー","すきー","skiing"
"2","調べる","しら|べる","to investigate"
"2","大会","たいかい","convention/tournament"
"2","友","とも","friend"
"2","中学校","ちゅうがっこう","junior high school"
"2","壊れる","こわ|れる","to be broken"
"2","父親","ちちおや","father"
"2","コンサート","こんさーと","concert"
"2","ドイツ","どいつ","Germany"
"2","教会","きょうかい","church"
"2","作業","さぎょう","work/operation"
"2","教育","きょういく","education"
"2","行動","こうどう","action/behavior"
"2","保険","ほけん","insurance"
"2","開始","かいし","start/commencement"
"2","急","きゅう","urgent/steep"
"2","デパート","でぱーと","department store"
"2","日曜日","にちようび","Sunday"
"2","反対","はんたい","opposition"
"2","推薦","すいせん","recommendation"
"2","戦争","せんそう","war"
"2","普通","ふつう","ordinary/normal"
"2","発見","はっけん","discovery"
"2","途中","とちゅう","on the way"
"2","耳","みみ","ear"
"2","これから","これから","from now on"
"2","間違える","まちが|える","to make a mistake"
"2","立場","たちば","position/standpoint"
"2","注目","ちゅうもく","notice/attention"
"2","横","よこ","side"
"2","原因","げんいん","cause"
"2","以前","いぜん","previously/before"
"2","新た","あら|た","new/fresh"
"2","危険","きけん","danger"
"2","電子","でんし","electronic/electron"
"2","分野","ぶんや","field/realm"
"2","食事","しょくじ","meal"
"2","物語","ものがたり","story/tale"
"2","祖父","そふ","grandfather"
"2","場合","ばあい","case/situation"
"2","気に入る","き|に|い|る","to like/be pleased with"
"2","貸す","か|す","to lend"
"2","学ぶ","まな|ぶ","to learn"
"2","ところで","ところで","by the way"
"2","無理","むり","impossible"
"2","人物","じんぶつ","person/character"
"2","免許","めんきょ","license"
"2","税金","ぜいきん","tax"
"2","シャツ","しゃつ","shirt"
"2","子","こ","child"
"2","西","にし","West"
"2","向こう","む|こう","over there/other side"
"2","悩み","なや|み","worry/trouble"
"2","必ず","かなら|ず","surely/always"
"2","日時","にちじ","date and time"
"2","国家","こっか","state/nation"
"2","足りる","た|りる","to be sufficient"
"2","政治","せいじ","politics"
"2","男性","だんせい","man/male"
"2","オーストラリア","おーすとらりあ","Australia"
"2","スカート","すかーと","skirt"
"2","会議","かいぎ","meeting/conference"
"2","覚える","おぼ|える","to remember/memorize"
"2","犯罪","はんざい","crime"
"2","留守","るす","absence"
"2","日","ひ","day/sun"
"2","歴史","れきし","history"
"2","卒業","そつぎょう","graduation"
"2","前","まえ","front/before"
"2","短い","みじか|い","short"
"2","自然","しぜん","nature"
"2","指輪","ゆびわ","ring"
"2","現在","げんざい","present time"
"2","同時","どうじ","same time"
"2","観光","かんこう","sightseeing"
"2","紹介","しょうかい","introduction"
"2","比べる","くら|べる","to compare"
"2","経済","けいざい","economy"
"2","大事","だいじ","important"
"2","実際","じっさい","reality/actual"
"2","部分","ぶぶん","part/section"
"2","文句","もんく","complaint"
"2","倒れる","たお|れる","to fall down/collapse"
"2","無料","むりょう","free of charge"
"2","クリスマス","くりすます","Christmas"
"2","文章","ぶんしょう","sentence/text"
"2","連絡","れんらく","contact/connection"
"2","夢","ゆめ","dream"
"2","半","はん","half"
"2","シャワー","しゃわー","shower"
"2","大半","たいはん","majority"
"2","科学","かがく","science"
"2","牛乳","ぎゅうにゅう","milk"
"2","女子","じょし","woman/girl"
"2","長女","ちょうじょ","eldest daughter"
"2","選手","せんしゅ","player/athlete"
"2","簡単","かんたん","simple/easy"
"2","方法","ほうほう","method"
"2","市民","しみん","citizen"
"2","技術","ぎじゅつ","technology/skill"
"2","釣り","つ|り","fishing"
"2","火","ひ","fire"
"2","美しい","うつく|しい","beautiful"
"2","期間","きかん","period/term"
"2","軽い","かる|い","light (weight)"
"2","発行","はっこう","issue/publication"
"2","法律","ほうりつ","law"
"2","事故","じこ","accident"
"2","当時","とうじ","at that time"
"2","低い","ひく|い","low"
"2","仕方","しかた","way/method"
"2","外出","がいしゅつ","going out"
"2","失敗","しっぱい","failure"
"2","情報","じょうほう","information"
"2","国語","こくご","national language (Japanese)"
"2","週","しゅう","week"
"2","以来","いらい","since"
"2","道路","どうろ","road"
"2","キャンプ","きゃんぷ","camping"
"2","下り","くだ|り","down-train/descent"
"2","出発","しゅっぱつ","departure"
"2","お茶","お|ちゃ","tea"
"2","内容","ないよう","content"
"2","確認","かくにん","confirmation"
"2","誘う","さそ|う","to invite"
"2","眼鏡","めがね","glasses"
"2","重要","じゅうよう","important"
"2","朝","あさ","morning"
"2","りんご","りんご","apple"
"2","今日中に","きょうじゅう|に","by the end of today"
"2","有名人","ゆうめいじん","celebrity"
"2","お金持ち","お|かねも|ち","rich person"
"2","パンダ","ぱんだ","panda"
"2","海外旅行","かいがいりょこう","overseas travel"
"2","実際に","じっさい|に","actually"
"2","パンツ","ぱんつ","underwear/pants"
"2","ではありません","ではありません","is not (polite)"
"2","越える","こ|える","to cross/exceed"
"2","事件","じけん","incident/case"
"2","ケーキ","けーき","cake"
"2","起こる","お|こる","to happen/occur"
"2","参加","さんか","participation"
"2","暗い","くら|い","dark"
"2","可能","かのう","possible"
"2","昼間","ひるま","daytime"
"2","決まる","き|まる","to be decided"
"2","商品","しょうひん","product"
"2","方向","ほうこう","direction"
"2","合う","あ|う","to fit/match"
"2","料金","りょうきん","fee/charge"
"2","妹","いもうと","younger sister"
"2","ものの","ものの","although"
"2","部下","ぶか","subordinate"
"2","人気","にんき","popularity"
"2","時期","じき","time/period"
"2","自身","じしん","oneself"
"2","位置","いち","position/location"
"2","泥棒","どろぼう","thief"
"2","後輩","こうはい","junior (at work/school)"
"2","村","むら","village"
"2","機会","きかい","opportunity"
"2","過去","かこ","past"
"2","が","が","but/subject marker"
"2","選挙","せんきょ","election"
"2","触る","さわ|る","to touch"
"2","不安","ふあん","anxiety/unease"
"2","起きる","お|きる","to get up/wake up"
"2","のに","のに","although/in order to"
"2","将来","しょうらい","future"
"2","残す","のこ|す","to leave behind"
"2","程度","ていど","degree/extent"
"2","発音","はつおん","pronunciation"
"2","教科書","きょうかしょ","textbook"
"2","机","つくえ","desk"
"2","楽しみ","たの|しみ","enjoyment/fun"
"2","集中","しゅうちゅう","concentration"
"2","マンション","まんしょん","apartment/mansion"
"2","住所","じゅうしょ","address"
"2","読み","よ|み","reading"
"2","乗る","の|る","to ride"
"2","機能","きのう","function"
"2","見学","けんがく","tour/inspection"
"2","一体","いったい","what on earth/unity"
"2","座る","すわ|る","to sit"
"2","今回","こんかい","this time"
"2","絶対に","ぜったい|に","absolutely"
"2","便利","べんり","convenient"
"2","青い","あお|い","blue"
"2","箱","はこ","box"
"2","通う","かよ|う","to commute"
"2","名","な","name"
"2","食品","しょくひん","food products"
"2","出かける","で|かける","to go out"
"2","地球","ちきゅう","Earth"
"2","地域","ちいき","region"
"2","決定","けってい","decision"
"2","全体","ぜんたい","whole/entire"
"2","おかしい","おかしい","strange/funny"
"2","代表","だいひょう","representative"
"2","時","とき","time/when"
"2","つまり","つまり","in short"
"2","判断","はんだん","judgment"
"2","茶","ちゃ","tea"
"2","全国","ぜんこく","nationwide"
"2","非常","ひじょう","emergency"
"2","二日","ふつか","two days/2nd day"
"2","確か","たし|か","certain/sure"
"2","身長","しんちょう","height"
"2","森","もり","forest"
"2","三日","みっか","three days/3rd day"
"2","拾う","ひろ|う","to pick up"
"2","天","てん","sky/heaven"
"2","相談","そうだん","consultation"
"2","中止","ちゅうし","cancellation"
"2","学習","がくしゅう","learning"
"2","ので","ので","because"
"2","自分自身","じぶんじしん","oneself"
"2","続ける","つづ|ける","to continue"
"2","ガソリン","がそりん","gasoline"
"2","間","あいだ","interval/between"
"2","直接","ちょくせつ","direct"
"2","事実","じじつ","fact"
"2","じゃない","じゃない","is not (casual)"
"2","電池","でんち","battery"
"2","責任","せきにん","responsibility"
"2","渡す","わた|す","to hand over"
"2","ドライブ","どらいぶ","drive"
"2","表現","ひょうげん","expression"
"2","物質","ぶっしつ","material/substance"
"2","階段","かいだん","stairs"
"2","報告","ほうこく","report"
"2","都市","とし","city"
"2","絶対","ぜったい","absolute"
"2","一生","いっしょう","whole life"
"2","大統領","だいとうりょう","president"
"2","同様","どうよう","similar"
"2","遊び","あそ|び","play/game"
"2","落ち込む","お|ち|こ|む","to feel down"
"2","交通","こうつう","traffic"
"2","水道","すいどう","water supply"
"2","一緒に","いっしょ|に","together"
"2","すごい","すごい","amazing"
"2","終わり","お|わり","end"
"2","年代","ねんだい","era/generation"
"2","寝る","ね|る","to sleep"
"2","制度","せいど","system"
"2","状況","じょうきょう","situation"
"2","期待","きたい","expectation"
"2","会員","かいいん","member"
"2","努力","どりょく","effort"
"2","以外","いがい","other than"
"2","結婚式","けっこんしき","wedding ceremony"
"2","放送","ほうそう","broadcast"
"2","効果","こうか","effect"
"2","青年","せいねん","youth"
"2","万","まん","ten thousand"
"2","二時","にじ","2 o'clock"
"2","教師","きょうし","teacher"
"2","メニュー","めにゅー","menu"
"2","午前中","ごぜんちゅう","in the morning"
"2","大変","たいへん","tough/awful"
"2","線","せん","line"
"2","書く","か|く","to write"
"2","言語","げんご","language"
"2","髪","かみ","hair"
"2","だ","だ","is (casual copula)"
"2","百万","ひゃくまん","one million"
"2","記録","きろく","record"
"2","開発","かいはつ","development"
"2","私","わたし","I/me"
"2","姉妹","しまい","sisters"
"2","記事","きじ","article/news"
"2","物価","ぶっか","prices"
"2","一般","いっぱん","general"
"2","汚い","きたな|い","dirty"
"2","工業","こうぎょう","industry"
"2","国民","こくみん","citizen"
"2","生じる","しょう|じる","to produce/occur"
"2","両方","りょうほう","both"
"2","いつか","いつか","someday"
"2","複雑","ふくざつ","complex"
"2","太陽","たいよう","sun"
"2","一年間","いちねんかん","one year"
"2","数字","すうじ","number"
"2","入る","はい|る","to enter"
"2","喫茶店","きっさてん","coffee shop"
"2","工事","こうじ","construction work"
"2","決して","けっ|して","never"
"2","時半","じはん","half past (time)"
"2","警察官","けいさつかん","police officer"
"2","活動","かつどう","activity"
"2","最高","さいこう","best/highest"
"2","要求","ようきゅう","demand/request"
"2","国会","こっかい","National Diet"
"2","本人","ほんにん","the person himself"
"2","生きる","い|きる","to live"
"2","九つ","ここの|つ","nine items"
"2","解決","かいけつ","solution"
"2","学年","がくねん","school year/grade"
"2","個人","こじん","individual"
"2","時","じ","o'clock"
"2","外国語","がいこくご","foreign language"
"2","名人","めいじん","master/expert"
"2","増加","ぞうか","increase"
"2","つもり","つもり","intention"
"2","さらに","さらに","furthermore"
"2","大いに","おお|いに","very/much"
"2","飲む","の|む","to drink"
"2","酒","さけ","alcohol/sake"
"2","示す","しめ|す","to show"
"2","人間","にんげん","human"
"2","南北","なんぼく","north and south"
"2","五日","いつか","five days/5th day"
"2","背","せ","back/stature"
"2","発売","はつばい","sale/release"
"2","変更","へんこう","change/modification"
"2","伝える","つた|える","to convey"
"2","経営","けいえい","management"
"2","成長","せいちょう","growth"
"2","優しい","やさ|しい","kind/gentle"
"2","手術","しゅじゅつ","surgery"
"2","光","ひかり","light"
"2","理解","りかい","understanding"
"2","関連","かんれん","connection"
"2","熱い","あつ|い","hot (thing)"
"2","完成","かんせい","completion"
"2","未来","みらい","future"
"2","事情","じじょう","circumstances"
"2","処理","しょり","processing"
"2","協力","きょうりょく","cooperation"
"2","四日","よっか","four days/4th day"
"2","基本","きほん","foundation/basics"
"2","招待","しょうたい","invitation"
"2","馬","うま","horse"
"2","住宅","じゅうたく","housing"
"2","熱","ねつ","heat/fever"
"2","機械","きかい","machine"
"2","文法","ぶんぽう","grammar"
"2","舞台","ぶたい","stage"
"2","ではない","ではない","is not"
"2","出口","でぐち","exit"
"2","ある","ある","there is/to have"
"2","帰り","かえ|り","return"
"2","バス停","ばすてい","bus stop"
"2","後","あと","after/later"
"2","販売","はんばい","sales/selling"
"2","多い","おお|い","many"
"2","結果","けっか","result"
"2","牛","うし","cow"
"2","人","ひと","person"
"2","意識","いしき","consciousness"
"2","東西","とうざい","east and west"
"2","守る","まも|る","to protect"
"2","塩","しお","salt"
"2","状態","じょうたい","condition"
"2","存在","そんざい","existence"
"2","スープ","すーぷ","soup"
"2","参考","さんこう","reference"
"2","残る","のこ|る","to remain"
"2","管理","かんり","management"
"2","正しい","ただ|しい","correct"
"2","もちろん","もちろん","of course"
"2","六日","むいか","six days/6th day"
"2","健康","けんこう","health"
"2","水","みず","water"
"2","殺す","ころ|す","to kill"
"2","許す","ゆる|す","to forgive"
"2","再び","ふたた|び","again"
"2","担当","たんとう","in charge"
"2","動き","うご|き","movement"
"2","一千","いっせん","one thousand"
"2","後半","こうはん","second half"
"2","企業","きぎょう","enterprise"
"2","図","ず","figure/chart"
"2","影響","えいきょう","influence"
"2","学者","がくしゃ","scholar"
"2","今週","こんしゅう","this week"
"2","様子","ようす","appearance/situation"
"2","住民","じゅうみん","resident"
"2","役割","やくわり","role"
"2","せんす","せんす","folding fan"
"2","相当","そうとう","considerable"
"2","成功","せいこう","success"
"2","池","いけ","pond"
"2","現代","げんだい","modern times"
"2","現実","げんじつ","reality"
"2","グラス","ぐらす","glass"
"2","季節","きせつ","season"
"2","実験","じっけん","experiment"
"2","九日","ここのか","nine days/9th day"
"2","精神","せいしん","spirit/mind"
"2","どうぞ","どうぞ","please/here you go"
"2","血","ち","blood"
"2","レポート","れぽーと","report"
"2","下車","げしゃ","getting off"
"2","流れ","なが|れ","flow"
"2","対象","たいしょう","target/object"
"2","職業","しょくぎょう","occupation"
"2","得意","とくい","good at/proud"
"2","壁","かべ","wall"
"2","都合","つごう","convenience"
"2","現場","げんば","scene/site"
"2","数学","すうがく","mathematics"
"2","本物","ほんもの","real thing"
"2","材料","ざいりょう","ingredients/materials"
"2","終える","お|える","to finish"
"2","心理","しんり","psychology"
"2","限る","かぎ|る","to limit"
"2","一時","いちじ","1 o'clock/temporarily"
"2","優勝","ゆうしょう","victory/championship"
"2","色","いろ","color"
"2","海岸","かいがん","coast/beach"
"2","公開","こうかい","opening to the public"
"2","手伝う","てつだ|う","to help"
"2","全員","ぜんいん","all members"
"2","実現","じつげん","realization"
"2","崩れる","くず|れる","to collapse"
"2","合格","ごうかく","passing (exam)"
"2","塾","じゅく","cram school"
"2","建設","けんせつ","construction"
"2","黄色","きいろ","yellow"
"2","西洋","せいよう","the West"
"2","道具","どうぐ","tool"
"2","成績","せいせき","grades"
"2","共通","きょうつう","common"
"2","割合","わりあい","ratio"
"2","実行","じっこう","execution"
"2","長年","ながねん","many years"
"2","重大","じゅうだい","serious/important"
"2","構成","こうせい","composition"
"2","冷たい","つめ|たい","cold (to touch)"
"2","患者","かんじゃ","patient"
"2","降りる","お|りる","to get off"
"2","同時に","どうじ|に","at the same time"
"2","中国","ちゅうごく","China"
"2","動物園","どうぶつえん","zoo"
"2","多少","たしょう","somewhat"
"2","店員","てんいん","shop assistant"
"2","医学","いがく","medical science"
"2","半年","はんとし","half a year"
"2","文明","ぶんめい","civilization"
"2","国際","こくさい","international"
"2","安定","あんてい","stability"
"2","置く","お|く","to place"
"2","指導","しどう","guidance"
"2","教授","きょうじゅ","professor"
"2","調査","ちょうさ","survey/investigation"
"2","出張","しゅっちょう","business trip"
"2","道","みち","road"
"2","高校生","こうこうせい","high school student"
"2","知識","ちしき","knowledge"
"2","残り","のこ|り","remainder"
"2","忙しい","いそが|しい","busy"
"2","鼻","はな","nose"
"2","権利","けんり","right/privilege"
"2","帽子","ぼうし","hat"
"2","基礎","きそ","foundation"
"2","サラリーマン","さらりーまん","salaryman"
"2","体験","たいけん","experience"
"2","拡大","かくだい","magnification/expansion"
"2","特徴","とくちょう","characteristic"
"2","感謝","かんしゃ","gratitude"
"2","からい","からい","spicy/salty"
"2","玄関","げんかん","entrance"
"2","デート","でーと","date"
"2","合計","ごうけい","sum/total"
"2","興味","きょうみ","interest"
"2","背中","せなか","back (body)"
"2","学会","がっかい","academic society"
"2","もうす","もうす","to say (humble)"
"2","上り","のぼ|り","ascent/up-train"
"2","本気","ほんき","seriousness"
"2","薬","くすり","medicine"
"2","行き","ゆ|き","bound for"
"2","面接","めんせつ","interview"
"2","高まる","たか|まる","to rise/increase"
"2","おじいさん","おじいさん","grandfather"
"2","電話をかける","でんわ|をかける","to make a phone call"
"2","気分が悪い","きぶん|が|わ|るい","to feel sick"
"2","三千","さんぜん","three thousand"
"2","何百","なんびゃく","hundreds"
"2","10時","じゅうじ","10 o'clock"
"2","近所","きんじょ","neighborhood"
"2","西口","にしぐち","west exit"
"2","五時","ごじ","5 o'clock"
"2","組織","そしき","organization"
"2","または","または","or"
"2","急ぐ","いそ|ぐ","to hurry"
"2","議論","ぎろん","discussion"
"2","傾向","けいこう","trend/tendency"
"2","胸","むね","chest"
"2","林","はやし","woods"
"2","食料","しょくりょう","food"
"2","夜","よる","night"
"2","殴る","なぐ|る","to hit/punch"
"2","出会う","であ|う","to meet (by chance)"
"2","発生","はっせい","occurrence"
"2","育てる","そだ|てる","to raise"
"2","火山","かざん","volcano"
"2","年齢","ねんれい","age"
"2","夕食","ゆうしょく","dinner"
"2","おじょうさん","お|じょう|さん","young lady (polite)"
"2","中央","ちゅうおう","central"
"2","大丈夫","だいじょうぶ","alright/okay"
"2","泳ぐ","およ|ぐ","to swim"
"2","ゼロ","ぜろ","zero"
"2","一言","ひとこと","single word"
"2","発言","はつげん","statement"
"2","希望","きぼう","hope"
"2","からて","からて","karate"
"2","太い","ふと|い","thick/fat"
"2","移動","いどう","movement/transfer"
"2","競争","きょうそう","competition"
"2","見事","みごと","splendid"
"2","契約","けいやく","contract"
"2","営業","えいぎょう","business/sales"
"2","一部","いちぶ","one part"
"2","収入","しゅうにゅう","income"
"2","計算","けいさん","calculation"
"2","靴下","くつした","socks"
"2","合わせる","あ|わせる","to combine/match"
"2","提案","ていあん","proposal"
"2","手段","しゅだん","means/way"
"2","関心","かんしん","concern/interest"
"2","弱い","よわ|い","weak"
"2","薄い","うす|い","thin"
"2","洗う","あら|う","to wash"
"2","農業","のうぎょう","agriculture"
"2","団体","だんたい","organization"
"2","適用","てきよう","application/adoption"
"2","ええ","ええ","yes"
"2","掃除","そうじ","cleaning"
"2","秋","あき","autumn"
"2","困難","こんなん","difficulty"
"2","向かう","む|かう","to head towards"
"2","サークル","さーくる","club/circle"
"2","休日","きゅうじつ","holiday"
"2","連続","れんぞく","continuation"
"2","意外","いがい","unexpected"
"2","どんな","どんな","what kind of"
"2","被害","ひがい","damage"
"2","実施","じっし","implementation"
"2","深い","ふか|い","deep"
"2","輸入","ゆにゅう","import"
"2","動かす","うご|かす","to move (something)"
"2","共同","きょうどう","joint/cooperation"
"2","斜め","ななめ","diagonal"
"2","遅れる","おく|れる","to be late"
"2","制限","せいげん","restriction"
"2","費用","ひよう","cost/expense"
"2","設計","せっけい","design/plan"
"2","価格","かかく","price"
"2","普段","ふだん","usually"
"2","祖母","そぼ","grandmother"
"2","湯","ゆ","hot water"
"2","もう１度","もういちど","once more"
"2","生命","せいめい","life"
"2","疑問","ぎもん","question/doubt"
"2","やる","やる","to do/give"
"2","世代","せだい","generation"
"2","感情","かんじょう","emotion"
"2","世間","せけん","world/society"
"2","場面","ばめん","scene/setting"
"2","首都","しゅと","capital city"
"2","留学","りゅうがく","studying abroad"
"2","資料","しりょう","materials/data"
"2","返す","かえ|す","to return (something)"
"2","失う","うしな|う","to lose"
"2","世話","せわ","care/help"
"2","規則","きそく","rule/regulation"
"2","同一","どういつ","identical"
"2","労働","ろうどう","labor"
"2","牛肉","ぎゅうにく","beef"
"2","支配","しはい","rule/control"
"2","消費","しょうひ","consumption"
"2","一家","いっか","whole family"
"2","一","いち","one"
"2","思想","しそう","thought/ideology"
"2","この間","この|あいだ","the other day"
"2","無事","ぶじ","safety"
"2","自動","じどう","automatic"
"2","住む","す|む","to live"
"2","特急","とっきゅう","limited express"
"2","洋服","ようふく","western clothes"
"2","監督","かんとく","director/manager"
"2","今夜","こんや","tonight"
"2","回復","かいふく","recovery"
"2","生かす","い|かす","to make use of"
"2","行う","おこな|う","to perform/conduct"
"2","検討","けんとう","consideration"
"2","咲く","さ|く","to bloom"
"2","条件","じょうけん","condition"
"2","明確","めいかく","clear"
"2","正式","せいしき","formal"
"2","交換","こうかん","exchange"
"2","一時間","いちじかん","one hour"
"2","雲","くも","cloud"
"2","月","つき","moon/month"
"2","感覚","かんかく","sense/feeling"
"2","記念","きねん","commemoration"
"2","貿易","ぼうえき","trade"
"2","事業","じぎょう","business/project"
"2","医療","いりょう","medical care"
"2","評価","ひょうか","evaluation"
"2","信頼","しんらい","trust"
"2","辞書","じしょ","dictionary"
"2","ほど","ほど","extent/degree"
"2","古代","こだい","ancient times"
"2","死ぬ","し|ぬ","to die"
"2","おじさん","おじさん","uncle"
"2","記者","きしゃ","reporter"
"2","したがって","したがって","therefore"
"2","老人","ろうじん","old person"
"2","主要","しゅよう","main/major"
"2","先日","せんじつ","the other day"
"2","カーテン","かーてん","curtain"
"2","人形","にんぎょう","doll"
"2","家賃","やちん","rent"
"2","豊か","ゆた|か","wealthy/abundant"
"2","嫌","いや","disagreeable/hateful"
"2","結局","けっきょく","eventually/after all"
"2","現状","げんじょう","current situation"
"2","もってくる","もってくる","to bring"
"2","強化","きょうか","strengthening"
"2","似合う","にあ|う","to suit/match"
"2","印象","いんしょう","impression"
"2","許可","きょか","permission"
"2","野球","やきゅう","baseball"
"2","前半","ぜんはん","first half"
"2","通信","つうしん","communication"
"2","六つ","むっ|つ","six items"
"2","日常","にちじょう","everyday life"
"2","列車","れっしゃ","train"
"2","だいぶ","だいぶ","considerably"
"2","円","えん","yen/circle"
"2","選択","せんたく","selection"
"2","指定","してい","designation"
"2","に対する","に|たい|する","towards/against"
"2","事務","じむ","office work"
"2","単位","たんい","unit/credit"
"2","地元","じもと","local"
"2","姿","すがた","figure/form"
"2","人類","じんるい","mankind"
"2","死亡","しぼう","death"
"2","活用","かつよう","utilization"
"2","有効","ゆうこう","valid/effective"
"2","ビジネス","びじねす","business"
"2","植物","しょくぶつ","plant"
"2","行事","ぎょうじ","event"
"2","発展","はってん","development"
"2","訪問","ほうもん","visit"
"2","周辺","しゅうへん","surroundings"
"2","感じ","かん|じ","feeling"
"2","下がる","さ|がる","to go down"
"2","年度","ねんど","fiscal year"
"2","成立","せいりつ","establishment"
"2","禁止","きんし","prohibition"
"2","突然","とつぜん","sudden"
"2","他人","たにん","stranger/others"
"2","父母","ふぼ","parents"
"2","命令","めいれい","order/command"
"2","つまらない","つまらない","boring"
"2","高度","こうど","altitude/advanced"
"2","風景","ふうけい","scenery"
"2","一定","いってい","constant/fixed"
"2","登場","とうじょう","appearance (on stage)"
"2","出席","しゅっせき","attendance"
"2","平均","へいきん","average"
"2","一番","いちばん","number one/most"
"2","地位","ちい","status/position"
"2","おそらく","おそらく","probably"
"2","周囲","しゅうい","surroundings"
"2","肩","かた","shoulder"
"2","彼","かれ","he/boyfriend"
"2","より","より","than"
"2","表面","ひょうめん","surface"
"2","製品","せいひん","product"
"2","喜ぶ","よろこ|ぶ","to be delighted"
"2","服","ふく","clothes"
"2","詳しい","くわ|しい","detailed"
"2","去年","きょねん","last year"
"2","否定","ひてい","denial"
"2","ジュース","じゅーす","juice"
"2","維持","いじ","maintenance"
"2","金額","きんがく","amount of money"
"2","金","かね","money"
"2","障害","しょうがい","obstacle/disability"
"2","利益","りえき","profit"
"2","末","すえ","end"
"2","消す","け|す","to erase/turn off"
"2","記憶","きおく","memory"
"2","出版","しゅっぱん","publication"
"2","訪ねる","たず|ねる","to visit"
"2","温度","おんど","temperature"
"2","鍋","なべ","pot/hot pot"
"2","同僚","どうりょう","colleague"
"2","到着","とうちゃく","arrival"
"2","交流","こうりゅう","exchange"
"2","用いる","もち|いる","to use"
"2","適当","てきとう","suitable/vague"
"2","画家","がか","painter/artist"
"2","独立","どくりつ","independence"
"2","借金","しゃっきん","debt"
"2","宗教","しゅうきょう","religion"
"2","素晴らしい","すば|らしい","wonderful"
"2","建築","けんちく","architecture"
"2","話題","わだい","topic"
"2","ひとりで","ひとりで","alone"
"2","予算","よさん","budget"
"2","攻撃","こうげき","attack"
"2","追う","お|う","to chase"
"2","誕生","たんじょう","birth"
"2","構造","こうぞう","structure"
"2","開催","かいさい","holding (event)"
"2","集団","しゅうだん","group/mass"
"2","ネクタイ","ねくたい","tie"
"2","良い","よ|い","good"
"2","訓練","くんれん","training"
"2","繰り返す","く|り|かえ|す","to repeat"
"2","主張","しゅちょう","claim/insistence"
"2","抱える","かか|える","to hold/carry"
"2","始めて","はじ|めて","for the first time"
"2","飾る","かざ|る","to decorate"
"2","宇宙","うちゅう","universe/space"
"2","供給","きょうきゅう","supply"
"2","始まり","はじ|まり","beginning"
"2","委員","いいん","committee member"
"2","見出し","みだ|し","headline"
"2","通常","つうじょう","ordinary/usual"
"2","作者","さくしゃ","author"
"2","演奏","えんそう","musical performance"
"2","味方","みかた","ally"
"2","水泳","すいえい","swimming"
"2","確実","かくじつ","certainty"
"2","並ぶ","なら|ぶ","to line up"
"2","鉄道","てつどう","railroad"
"2","改善","かいぜん","improvement"
"2","批判","ひはん","criticism"
"2","特定","とくてい","specific"
"2","苦手","にがて","poor at/dislike"
"2","検査","けんさ","inspection/test"
"2","巨大","きょだい","huge"
"2","輸出","ゆしゅつ","export"
"2","設備","せつび","equipment/facilities"
"2","以後","いご","after this"
"2","単に","たん|に","simply"
"2","砂","すな","sand"
"2","範囲","はんい","range/scope"
"2","容易","ようい","easy"
"2","どう","どう","how"
"2","昨日","きのう","yesterday"
"2","近代","きんだい","modern ages"
"2","見方","みかた","viewpoint"
"2","財産","ざいさん","property/fortune"
"2","背景","はいけい","background"
"2","来","らい","next/coming"
"2","ドア","どあ","door"
"2","果物","くだもの","fruit"
"2","論文","ろんぶん","thesis/essay"
"2","地理","ちり","geography"
"2","現象","げんしょう","phenomenon"
"2","案内","あんない","guidance/information"
"2","流す","なが|す","to flow/drain"
"2","痛い","いた|い","painful"
"2","不満","ふまん","dissatisfaction"
"2","屋根","やね","roof"
"2","表情","ひょうじょう","facial expression"
"2","知事","ちじ","governor"
"2","寒い","さむ|い","cold"
"2","年中","ねんじゅう","all year round"
"2","逮捕","たいほ","arrest"
"2","備える","そな|える","to prepare/equip"
"2","不思議","ふしぎ","strange/mystery"
"2","だから","だから","so/therefore"
"2","しゃべる","しゃべる","to chat"
"2","怖い","こわ|い","scary"
"2","脱ぐ","ぬ|ぐ","to take off (clothes)"
"2","語学","ごがく","language study"
"2","差別","さべつ","discrimination"
"2","なんか","なんか","something like"
"2","残念","ざんねん","regrettable"
"2","楽しむ","たの|しむ","to enjoy"
"2","価値","かち","value"
"2","芸術","げいじゅつ","art"
"2","笑い","わら|い","laughter"
"2","翻訳","ほんやく","translation"
"2","提出","ていしゅつ","submission"
"2","払う","はら|う","to pay"
"2","比較","ひかく","comparison"
"2","就職","しゅうしょく","finding employment"
"2","登る","のぼ|る","to climb"
"2","重ねる","かさ|ねる","to pile up"
"2","なる","なる","to become"
"2","議会","ぎかい","diet/congress"
"2","食う","く|う","to eat (male)"
"2","一日","ついたち","1st day of month"
"2","前年","ぜんねん","previous year"
"2","分ける","わ|ける","to divide/share"
"2","是非","ぜひ","certainly"
"2","スプーン","すぷーん","spoon"
"2","運","うん","luck/fortune"
"2","後者","こうしゃ","the latter"
"2","分析","ぶんせき","analysis"
"2","洗濯","せんたく","laundry"
"2","晩","ばん","evening"
"2","広場","ひろば","square/plaza"
"2","奥","おく","inner part/back"
"2","桜","さくら","cherry blossom"
"2","適切","てきせつ","appropriate"
"2","別れ","わか|れ","parting"
"2","単純","たんじゅん","simple"
"2","焼く","や|く","to bake/burn"
"2","鏡","かがみ","mirror"
"2","自動車","じどうしゃ","automobile"
"2","広げる","ひろ|げる","to spread/expand"
"2","型","かた","type/model"
"2","できるだけ","できるだけ","as much as possible"
"2","大気","たいき","atmosphere"
"2","業者","ぎょうしゃ","trader/merchant"
"2","涙","なみだ","tear"
"2","笑顔","えがお","smiling face"
"2","学問","がくもん","scholarship"
"2","終了","しゅうりょう","end/expiration"
"2","追加","ついか","addition"
"2","態度","たいど","attitude"
"2","製造","せいぞう","manufacture"
"2","伝統","でんとう","tradition"
"2","限界","げんかい","limit"
"2","解説","かいせつ","explanation"
"2","少なくとも","すく|なくとも","at least"
"2","茶色","ちゃいろ","brown"
"2","油","あぶら","oil"
"2","長期","ちょうき","long term"
"2","曜日","ようび","day of the week"
"2","なさる","なさる","to do (honorific)"
"2","神経","しんけい","nerve"
"2","保存","ほぞん","preservation"
"2","体育","たいいく","physical education"
"2","そろそろ","そろそろ","soon/by now"
"2","議員","ぎいん","legislator"
"2","雰囲気","ふんいき","atmosphere"
"2","国土","こくど","national land"
"2","一種","いっしゅ","species/kind"
"2","事態","じたい","situation"
"2","速度","そくど","speed"
"2","信用","しんよう","trust"
"2","依頼","いらい","request"
"2","自殺","じさつ","suicide"
"2","大使","たいし","ambassador"
"2","年月","としつき","months and years"
"2","温泉","おんせん","hot spring"
"2","息","いき","breath"
"2","安心","あんしん","relief"
"2","日中","にっちゅう","daytime"
"2","私立","しりつ","private (institution)"
"2","裁判","さいばん","trial"
"2","基準","きじゅん","standard"
"2","贈る","おく|る","to send/give"
"2","ほとんど","ほとんど","mostly"
"2","入社","にゅうしゃ","joining a company"
"2","たまに","たまに","occasionally"
"2","水分","すいぶん","moisture"
"2","整備","せいび","maintenance"
"2","世の中","よ|の|なか","society/world"
"2","読者","どくしゃ","reader"
"2","観察","かんさつ","observation"
"2","操作","そうさ","operation"
"2","下げる","さ|げる","to lower"
"2","憲法","けんぽう","constitution"
"2","値段","ねだん","price"
"2","民間","みんかん","private (civilian)"
"2","通過","つうか","passage/transit"
"2","急速","きゅうそく","rapid"
"2","慣れる","な|れる","to get used to"
"2","展開","てんかい","development"
"2","過程","かてい","process"
"2","一切","いっさい","all/everything"
"2","体力","たいりょく","physical strength"
"2","留学生","りゅうがくせい","international student"
"2","痛み","いた|み","pain"
"2","武器","ぶき","weapon"
"2","親","おや","parent"
"2","皿","さら","plate"
"2","台所","だいどころ","kitchen"
"2","裏","うら","reverse side"
"2","承認","しょうにん","approval"
"2","受験","じゅけん","taking an exam"
"2","ください","ください","please"
"2","文書","ぶんしょ","document"
"2","盛ん","さか|ん","prosperous/popular"
"2","進学","しんがく","entering higher education"
"2","改正","かいせい","revision"
"2","断る","ことわ|る","to refuse"
"2","流行","りゅうこう","fashion/trend"
"2","気温","きおん","temperature"
"2","七日","なのか","seven days/7th day"
"2","ほんの","ほんの","mere/only"
"2","現金","げんきん","cash"
"2","グラム","ぐらむ","gram"
"2","注","ちゅう","note/annotation"
"2","手続き","てつづ|き","procedure"
"2","人工","じんこう","artificial"
"2","切手","きって","stamp"
"2","満足","まんぞく","satisfaction"
"2","撮影","さつえい","photography"
"2","孫","まご","grandchild"
"2","安い","やす|い","cheap"
"2","通学","つうがく","commuting to school"
"2","表","おもて","surface/front"
"2","姿勢","しせい","posture"
"2","おっしゃる","おっしゃる","to say (honorific)"
"2","まで","まで","until"
"2","郵便局","ゆうびんきょく","post office"
"2","味","あじ","taste"
"2","具合","ぐあい","condition"
"2","親友","しんゆう","best friend"
"2","ただ","ただ","just/free"
"2","代わり","か|わり","substitute"
"2","かぶる","かぶる","to put on (head)"
"2","格好","かっこう","appearance"
"2","魅力","みりょく","charm"
"2","望む","のぞ|む","to desire"
"2","八日","ようか","eight days/8th day"
"2","暮らし","く|らし","living/livelihood"
"2","面倒","めんどう","trouble/difficulty"
"2","深刻","しんこく","serious"
"2","結構","けっこう","splendid/enough"
"2","踊り","おど|り","dance"
"2","八つ","やっ|つ","eight items"
"2","国立","こくりつ","national"
"2","現地","げんち","local"
"2","抵抗","ていこう","resistance"
"2","不明","ふめい","unknown"
"2","物理","ぶつり","physics"
"2","込む","こ|む","to be crowded"
"2","複数","ふくすう","plural/multiple"
"2","面白い","おもしろ|い","interesting"
"2","浴びる","あ|びる","to bathe"
"2","かつ","かつ","and/moreover"
"2","編集","へんしゅう","editing"
"2","課題","かだい","task/assignment"
"2","集まる","あつ|まる","to gather"
"2","日曜","にちよう","Sunday"
"2","コンピューター","こんぴゅーたー","computer"
"2","中身","なかみ","contents"
"2","罪","つみ","sin/crime"
"2","模様","もよう","pattern"
"2","支持","しじ","support"
"2","広がる","ひろ|がる","to spread"
"2","務める","つと|める","to serve/work"
"2","恋","こい","love"
"2","坂","さか","slope"
"2","わたし達","わたし|たち","we"
"2","姉","あね","older sister"
"2","喜び","よろこ|び","joy"
"2","下ろす","お|ろす","to lower/withdraw"
"2","花火","はなび","fireworks"
"2","我々","われわれ","we"
"2","風呂","ふろ","bath"
"2","苦労","くろう","hardship"
"2","香り","かお|り","scent"
"2","破る","やぶ|る","to tear/break"
"2","鉛筆","えんぴつ","pencil"
"2","増やす","ふ|やす","to increase"
"2","隣","となり","neighbor"
"2","久しぶり","ひさ|しぶり","after a long time"
"2","渡る","わた|る","to cross"
"2","死体","したい","corpse"
"2","すでに","すでに","already"
"2","国境","こっきょう","border"
"2","まもなく","まもなく","soon"
"2","分かりにくい","わ|かりにくい","hard to understand"
"2","影","かげ","shadow"
"2","付き合う","つ|き|あ|う","to date/associate"
"2","あそこ","あそこ","over there"
"2","保証","ほしょう","guarantee"
"2","弁当","べんとう","box lunch"
"2","猿","さる","monkey"
"2","傷","きず","wound"
"2","飛ぶ","と|ぶ","to fly"
"2","ダメ","だめ","no good"
"2","当たる","あ|たる","to hit/win"
"2","抑える","おさ|える","to suppress"
"2","元","もと","origin/former"
"2","どうしよう","どうしよう","what should I do"
"2","おばあさん","おばあさん","grandmother"
"2.1","花だん","か|だん","flower bed"
"2.1","花たば","はな|たば","bouquet"
"2.1","花びら","はな|びら","flower petal"
"2.1","木かげ","こ|かげ","shade of a tree"
"2.1","にわ木","にわ|き","garden tree"
"2.1","木目","もくめ","wood grain"
"2.1","九月","くがつ","September"
"2.1","九こ","きゅう|こ","nine pieces"
"2.1","九つ","ここの|つ","nine things"
"2.1","一年生","いちねんせい","first grade student"
"2.1","一ぴき","いっ|ぴき","one animal (small)"
"2.1","一つ","ひと|つ","one thing"
"2.1","ざっ草","ざっ|そう","weeds"
"2.1","草もち","くさ|もち","rice cake with mugwort"
"2.1","草はら","くさ|はら","grassy field"
"2.1","ちょ金","ちょ|きん","savings"
"2.1","金いろ","きん|いろ","gold color"
"2.1","お金","お|かね","money"
"2.1","十日","とおか","10th day"
"2.1","十月","じゅうがつ","October"
"2.1","十年","じゅうねん","ten years"
"2.1","二日","ふつか","2nd day"
"2.1","二こ","に|こ","two pieces"
"2.1","二つ","ふた|つ","two things"
"2.1","ほう石","ほう|せき","gem / jewel"
"2.1","じ石","じ|しゃく","magnet"
"2.1","小石","こいし","pebble"
"2.1","赤土","あかつち","red clay / red soil"
"2.1","土足","どそく","with shoes on / muddy feet"
"2.1","百日","ひゃくにち","100 days"
"2.1","百円","ひゃくえん","100 yen"
"2.1","百年","ひゃくねん","100 years"
"2.1","三本","さんぼん","three cylindrical objects"
"2.1","三こ","さん|こ","three pieces"
"2.1","三つ","みっ|つ","three things"
"2.1","ほら貝","ほら|がい","conch shell"
"2.1","まき貝","まき|がい","spiral shell"
"2.1","貝がら","かい|がら","shell"
"2.1","ふじ山","ふじ|さん","Mt. Fuji"
"2.1","山いも","やま|いも","yam"
"2.1","山みち","やま|みち","mountain path"
"2.1","千人","せんにん","1000 people"
"2.1","千円","せんえん","1000 yen"
"2.1","千年","せんねん","1000 years"
"2.1","四月","しがつ","April"
"2.1","四こ","よん|こ","four pieces"
"2.1","四つ","よっ|つ","four things"
"2.1","虫かご","むし|かご","insect cage"
"2.1","こん虫","こん|ちゅう","insect"
"2.1","すず虫","すず|むし","bell cricket"
"2.1","川べり","かわ|べり","riverbank"
"2.1","川しも","かわ|しも","downstream"
"2.1","川かみ","かわ|かみ","upstream"
"2.1","日じ","にち|じ","date and time"
"2.1","一日","いちにち","one day"
"2.1","三日","みっか","3rd day"
"2.1","五わ","ご|わ","five birds"
"2.1","五こ","ご|こ","five pieces"
"2.1","五つ","いつ|つ","five things"
"2.1","犬ぞり","いぬ|ぞり","dog sled"
"2.1","白い犬","しろいいぬ","white dog"
"2.1","名犬","めいけん","faithful dog / famous dog"
"2.1","山林","さんりん","mountain forest"
"2.1","まつ林","まつ|ばやし","pine forest"
"2.1","竹林","ちくりん","bamboo grove"
"2.1","まん月","まん|げつ","full moon"
"2.1","二月","にがつ","February"
"2.1","月見","つきみ","moon viewing"
"2.1","六本","ろっぽん","six cylindrical objects"
"2.1","六こ","ろっ|こ","six pieces"
"2.1","六つ","むっ|つ","six things"
"2.1","田うえ","た|うえ","rice planting"
"2.1","水田","すいでん","paddy field"
"2.1","田んぼ","たん|ぼ","rice field"
"2.1","青森","あおもり","Aomori (place)"
"2.1","森林","しんりん","forest"
"2.1","森の中","もりのなか","in the forest"
"2.1","火のこ","ひ|のこ","sparks / fire sparks"
"2.1","火山","かざん","volcano"
"2.1","火じ","か|じ","fire / conflagration"
"2.1","七いろ","なな|いろ","seven colors"
"2.1","七月","しちがつ","July"
"2.1","七つ","なな|つ","seven things"
"2.1","年より","とし|より","elderly person"
"2.1","年上","としうえ","older / senior"
"2.1","竹わ","ちく|わ","chikuwa (fish cake)"
"2.1","竹やぶ","たけ|やぶ","bamboo thicket"
"2.1","竹うま","たけ|うま","stilts"
"2.1","水どう","すい|どう","water supply"
"2.1","水草","みず|くさ","water plant"
"2.1","水玉","みず|たま","polka dot / water drop"
"2.1","八日","ようか","8th day"
"2.1","八月","はちがつ","August"
"2.1","八つ","やっ|つ","eight things"
"2.1","き立","き|りつ","stand up"
"2.1","立てる","た|てる","to stand something up"
"2.1","立つ","た|つ","to stand"
"2.1","かい力","かい|りき","superhuman strength"
"2.1","学力","がくりょく","academic ability"
"2.1","力もち","ちから|もち","strong person"
"2.1","大きい","おお|きい","big"
"2.1","大へん","たい|へん","difficult / very"
"2.1","大すき","だい|すき","love / like a lot"
"2.1","空ばこ","から|ばこ","empty box"
"2.1","空いろ","そら|いろ","sky blue"
"2.1","空気","くうき","air / atmosphere"
"2.1","休じつ","きゅう|じつ","holiday / day off"
"2.1","休める","やす|める","to rest (something)"
"2.1","休む","やす|む","to rest"
"2.1","人口","じんこう","population"
"2.1","口べに","くち|べに","lipstick"
"2.1","口ぶえ","くち|ぶえ","whistle"
"2.1","中にわ","なか|にわ","courtyard"
"2.1","中学校","ちゅうがっこう","middle school"
"2.1","一日中","いちにちじゅう","all day long"
"2.1","天ごく","てん|ごく","heaven"
"2.1","天の川","あまのがわ","Milky Way"
"2.1","天気","てんき","weather"
"2.1","出ぱつ","しゅっ|ぱつ","departure"
"2.1","出る","で|る","to exit / to leave"
"2.1","出す","だ|す","to take out / to submit"
"2.1","目てき","もく|てき","purpose / goal"
"2.1","目つき","め|つき","look (in eyes)"
"2.1","目と口","めとくち","eyes and mouth"
"2.1","小さい","ちい|さい","small"
"2.1","小学校","しょうがっこう","elementary school"
"2.1","げん気","げん|き","healthy / energetic"
"2.1","気もち","き|もち","feeling"
"2.1","入り口","いりぐち","entrance"
"2.1","入学","にゅうがく","school admission"
"2.1","入る","はい|る","to enter"
"2.1","はく手","はく|しゅ","applause"
"2.1","手くび","て|くび","wrist"
"2.1","右手","みぎて","right hand"
"2.1","上ぎ","うわ|ぎ","jacket / outerwear"
"2.1","上げる","あ|げる","to raise"
"2.1","木の上","きのうえ","on the tree"
"2.1","雨ぐも","あま|ぐも","rain cloud"
"2.1","雨天","うてん","rainy weather"
"2.1","雨ふり","あめ|ふり","rainfall / rainy"
"2.1","女と男","おんなとおとこ","woman and man"
"2.1","女の人","おんなのひと","woman"
"2.1","女子","じょし","girl / woman"
"2.1","一足","いっ|そく","one pair (of shoes)"
"2.1","足くび","あし|くび","ankle"
"2.1","足あと","あし|あと","footprint"
"2.1","下校","げこう","coming home from school"
"2.1","下げる","さ|げる","to lower"
"2.1","木の下","きのした","under the tree"
"2.1","夕ぐれ","ゆう|ぐれ","dusk / twilight"
"2.1","夕がた","ゆう|がた","evening"
"2.1","夕日","ゆうひ","setting sun"
"2.1","男子","だんし","boy / male"
"2.1","男の人","おとこのひと","man"
"2.1","男の子","おとこのこ","boy"
"2.1","目と耳","めとみみ","eyes and ears"
"2.1","耳うち","みみ|うち","whispering in ear"
"2.1","耳たぶ","みみ|たぶ","earlobe"
"2.1","左足","ひだりあし","left foot"
"2.1","左がわ","ひだり|がわ","left side"
"2.1","左右","さゆう","left and right"
"2.1","空白","くうはく","blank space"
"2.1","白い花","しろいはな","white flower"
"2.1","白ぐみ","しろ|ぐみ","white team"
"2.1","子犬","こいぬ","puppy"
"2.1","子ども","こ|ども","child"
"2.1","音いろ","ね|いろ","tone color / timbre"
"2.1","雨の音","あめのおと","sound of rain"
"2.1","音ぷ","おん|ぷ","musical note"
"2.1","右がわ","みぎ|がわ","right side"
"2.1","青空","あおぞら","blue sky"
"2.1","青年","せいねん","youth / young man"
"2.1","青い","あお|い","blue"
"2.1","人げん","にん|げん","human"
"2.1","めい人","めい|じん","master / expert"
"2.1","人ごみ","ひと|ごみ","crowd of people"
"2.1","見学","けんがく","field trip / study"
"2.1","見える","み|える","to be visible"
"2.1","見る","み|る","to see"
"2.1","円けい","えん|けい","circular shape"
"2.1","円ばん","えん|ばん","disk"
"2.1","円い","まる|い","round"
"2.1","赤はん","せき|はん","red rice (festive)"
"2.1","赤ちゃん","あか|ちゃん","baby"
"2.1","赤い車","あかいくるま","red car"
"2.1","早める","はや|める","to hasten"
"2.1","早足","はやあし","quick pace"
"2.1","早い","はや|い","early / fast"
"2.1","本名","ほんみょう","real name"
"2.1","名じん","めい|じん","master / expert"
"2.1","名まえ","な|まえ","name"
"2.1","正かい","せい|かい","correct answer"
"2.1","正じき","しょう|じき","honest"
"2.1","正しい","ただ|しい","correct / right"
"2.1","てん字","てん|じ","braille"
"2.1","すう字","すう|じ","number / digit"
"2.1","かん字","かん|じ","kanji characters"
"2.1","こく王","こく|おう","king"
"2.1","王かん","おう|かん","crown"
"2.1","王さま","おう|さま","king"
"2.1","文なし","もん|なし","penniless"
"2.1","文がく","ぶん|がく","literature"
"2.1","さく文","さく|ぶん","composition / essay"
"2.1","玉手ばこ","たまて|ばこ","Pandora's box"
"2.1","百円玉","ひゃくえんだま","100 yen coin"
"2.1","玉虫","たまむし","jewel beetle"
"2.1","本とう","ほん|とう","truth / really"
"2.1","本だな","ほん|だな","bookshelf"
"2.1","え本","え|ほん","picture book"
"2.1","きぬ糸","きぬ|いと","silk thread"
"2.1","赤い糸","あかいいと","red thread"
"2.1","白い糸","しろいいと","white thread"
"2.1","学ぶ","まな|ぶ","to learn"
"2.1","小学生","しょうがくせい","elementary student"
"2.1","学年","がくねん","school grade"
"2.1","車りん","しゃ|りん","wheel"
"2.1","でん車","でん|しゃ","train"
"2.1","青い車","あおいくるま","blue car"
"2.1","てん校","てん|こう","changing schools"
"2.1","校てい","こう|てい","schoolyard"
"2.1","山村","さんそん","mountain village"
"2.1","町と村","まちとむら","towns and villages"
"2.1","村の人","むらのひと","villager"
"2.1","足の先","あしのさき","toes / tip of foot"
"2.1","先とう","せん|とう","head / lead"
"2.1","先生","せんせい","teacher"
"2.1","町村","ちょうそん","towns and villages"
"2.1","町の中","まちのなか","in the town"
"2.1","町なみ","まち|なみ","townscape"
"2.1","生もの","なま|もの","raw food"
"2.1","生きる","い|きる","to live"
"2.1","生む","う|む","to give birth"`;

// --- UI & Setup Helpers ---

function loadPreset() {
  const val = document.getElementById("preset-list").value;
  if (val === "example") {
    document.getElementById("csv-input").value = EXAMPLE_CSV;
  } else {
    document.getElementById("csv-input").value = "";
  }
}

function toggleGuides() {
  const container = document.getElementById("canvas-container");
  const checkbox = document.getElementById("guide-toggle");
  if (checkbox.checked) container.classList.add("show-guides");
  else container.classList.remove("show-guides");
}

function restart() {
  location.reload();
}

function parseCSV(text) {
  const lines = text.trim().split("\n");
  const data = [];
  const parseLine = (line) => {
    const result = [];
    let current = "";
    let inQuote = false;
    for (let i = 0; i < line.length; i++) {
      const char = line[i];
      if (char === '"') inQuote = !inQuote;
      else if (char === "," && !inQuote) {
        result.push(current);
        current = "";
      } else current += char;
    }
    result.push(current);
    return result;
  };

  lines.forEach((line) => {
    if (!line.trim()) return;
    const cols = parseLine(line).map((c) => c.trim());
    if (cols.length >= 4 && cols[1] !== "kanji") {
      data.push({
        tags: cols[0],
        kanji: cols[1],
        readingRaw: cols[2],
        def: cols[3],
      });
    }
  });
  return data;
}

function isKana(char) {
  // Range covers Hiragana, Katakana, and prolonged sound mark (ー)
  return /[\u3040-\u309f\u30a0-\u30ff\u30fc]/.test(char);
}

// --- Display Rendering ---

function updateStatsUI(stats, currentWordIndex, totalWords) {
  // document.getElementById("stat-perfect").innerText = stats.perfect;
  // document.getElementById("stat-imperfect").innerText = stats.imperfect;
  document.getElementById("stat-progress").innerText =
    `${currentWordIndex}/${totalWords}`;
}

function updateWordProgress(kanjiArray, currentIndex) {
  const container = document.getElementById("word-progress-display");
  container.innerHTML = "";
  kanjiArray.forEach((char, idx) => {
    const span = document.createElement("span");
    span.textContent = char;
    if (idx < currentIndex) span.className = "correct";
    else if (idx === currentIndex) span.className = "current-char-highlight";
    else if (isKana(char)) span.className = "kana-char";
    else span.className = "pending-char";

    container.appendChild(span);
  });
}

function showReviewScreen(
  isFinish,
  currentWordIndex,
  studyList,
  sessionResults,
) {
  document.getElementById("study-section").style.display = "none";
  document.getElementById("review-section").style.display = "flex";

  const grid = document.getElementById("review-grid");
  grid.innerHTML = "";

  const title = document.getElementById("review-title");
  title.textContent = isFinish ? "Session Complete!" : "Review Checkpoint";

  const btn = document.getElementById("review-continue-btn");
  btn.style.display = isFinish ? "none" : "block";

  let startIndex = 0;
  if (!isFinish) {
    startIndex = Math.max(0, currentWordIndex - 10);
  }

  const limit = currentWordIndex;

  for (let i = startIndex; i < limit; i++) {
    const data = studyList[i];
    const res = sessionResults[i];
    if (!res) continue;

    const card = document.createElement("div");
    card.className = `review-card ${res.perfect ? "perfect" : "imperfect"}`;

    let readingDisp = data.readingRaw.replace("|", "");

    card.innerHTML = `
        <div class="review-kanji">${data.kanji}</div>
        <div class="review-reading">${readingDisp}</div>
        <div class="review-def">${data.def}</div>
        <div class="review-stats">${
          res.perfect ? "Perfect" : "Review Needed"
        }</div>
      `;

    card.onclick = () => {
      window.open(
        `https://jotoba.de/search/0/${encodeURIComponent(data.kanji)}`,
        "_blank",
      );
    };

    grid.appendChild(card);
  }
}

// --- Calligraphy Engine Wrappers ---

function initCalligraphy(width, height) {
  var canvas = $("#write-canvas");
  var layeredCanvas = $("#layered-canvas");
  var handCanvas = $("#hand-canvas");
  var canvasE = canvas.get(0);
  var layeredCanvasE = layeredCanvas.get(0);

  canvasE.width = width;
  canvasE.height = height;
  layeredCanvasE.width = width;
  layeredCanvasE.height = height;
  handCanvas[0].width = width;
  handCanvas[0].height = height;

  try {
    Calligraphy.Writer.Shared.StrokeEngine =
      new Calligraphy.Writer.StrokeEngine(
        canvasE.width,
        canvasE.height,
        canvas,
        layeredCanvasE,
      );
    Calligraphy.Writer.Shared.StrokeManager =
      new Calligraphy.Writer.StrokeManager(
        handCanvas,
        Calligraphy.Writer.Shared.StrokeEngine,
      );
    Calligraphy.Writer.Shared.StrokeManager.isHandVisible = false;
    Calligraphy.Writer.Shared.StrokeManager.start();
    Calligraphy.Writer.Shared.StrokeManager.setBrushOpacity(1);
  } catch (e) {
    console.error("Engine Error", e);
  }
}

function clearCanvas() {
  if (Calligraphy.Writer.Shared.StrokeManager) {
    Calligraphy.Writer.Shared.StrokeManager.clearHistory();
  }
}

function undoStroke() {
  if (Calligraphy.Writer.Shared.StrokeManager) {
    Calligraphy.Writer.Shared.StrokeManager.undoStroke();
  }
}

function setBrush(name) {
  if (Calligraphy.Writer.Shared.StrokeManager) {
    Calligraphy.Writer.Shared.StrokeManager.selectBrush(name);
  }
}

function toggleOutline(writerInstance) {
  if (writerInstance) {
    writerInstance.showOutline();
    setTimeout(() => writerInstance.hideOutline(), 1000);
  }
}
