var kanken9kanji = `引羽雲園遠何科夏家歌画回会海絵外角楽活間丸岩顔汽記帰弓牛魚京強教近兄形計元言原戸古午後語工公広交光考行高黄合谷国黒今才細作算止市矢姉思紙寺自時室社弱首秋週春書少場色食心新親図数西声星晴切雪船線前組走多太体台地池知茶昼長鳥朝直通弟店点電刀冬当東答頭同道読内南肉馬売買麦半番父風分聞米歩母方北毎妹万明鳴毛門夜野友用曜来里理話`;
var kanken10kanji = `一右雨円王音下火花貝学気九休玉金空月犬見五口校左三山子四糸字耳七車手十出女小上森人水正生青夕石赤千川先早草足村大男竹中虫町天田土二日入年白八百文木本名目立力林六`;

var kanken10 = `"tags","kanji","readings","definition"
"kanken-10","一番","いち|ばん","number one; first"
"kanken-10","二月一日","に|がつ|つい|たち","February 1st"
"kanken-10","水を一口のむ","みず|を|ひと|くち|の|む","drink a mouthful of water"
"kanken-10","一人","ひと|り","one person"
"kanken-10","右手","みぎ|て","right hand"
"kanken-10","左右を見る","さ|ゆう|を|み|る","look left and right"
"kanken-10","車が右折する","くるま|が|う|せつ|す|る","car turns right"
"kanken-10","雨がさ","あま|がさ","rain umbrella"
"kanken-10","雨天中止","う|てん|ちゅう|し","canceled due to rain"
"kanken-10","大雨のひがい","おお|あめ|の|ひ|が|い","damage from heavy rain"
"kanken-10","一円玉","いち|えん|だま","one yen coin"
"kanken-10","空とぶ円ばん","そら|と|ぶ|えん|ばん","flying saucer"
"kanken-10","円くなっておどる","まる|く|な|っ|て|お|ど|る","dance in a circle"
"kanken-10","王国","おう|こく","kingdom"
"kanken-10","王子さま","おう|じ|さ|ま","prince"
"kanken-10","ホームラン王になる","ほ|ー|む|ら|ん|おう|に|な|る","become the home run king"
"kanken-10","足音","あし|おと","footsteps"
"kanken-10","音楽","おん|がく","music"
"kanken-10","福音","ふく|いん","good news; gospel"
"kanken-10","すばらしい音色","す|ば|ら|し|い|ね|い|ろ","wonderful tone quality"
"kanken-10","地下","ち|か","underground"
"kanken-10","下校","げ|こう","coming home from school"
"kanken-10","足下","あし|もと","at one's feet"
"kanken-10","川下に下る","かわ|しも|に|くだ|る","go downstream"
"kanken-10","花火","はな|び","fireworks"
"kanken-10","火事","か|じ","fire; conflagration"
"kanken-10","火照る","ほ|て|る","to feel hot; to flush"
"kanken-10","火をけす","ひ|を|け|す","extinguish a fire"
"kanken-10","草花","くさ|ばな","flowering plants"
"kanken-10","花びん","か|びん","flower vase"
"kanken-10","お花見をたのしむ","お|はな|み|を|た|の|し|む","enjoy flower viewing"
"kanken-10","貝がら","かい|がら","seashell"
"kanken-10","さくら貝","さ|く|ら|がい","tellin shell"
"kanken-10","はまべで貝をひろう","は|ま|べ|で|かい|を|ひ|ろ|う","pick up shells on the beach"
"kanken-10","学校","がっ|こう","school"
"kanken-10","入学","にゅう|がく","school admission"
"kanken-10","漢字を学ぶ","かん|じ|を|まな|ぶ","learn kanji"
"kanken-10","天気","てん|き","weather"
"kanken-10","気配","け|はい","sign; indication"
"kanken-10","早おきは気持ちがよい","はや|お|き|は|き|も|ち|が|よ|い","waking up early feels good"
"kanken-10","おいしい空気","お|い|し|い|くう|き","fresh air"
"kanken-10","九月九日","く|がつ|ここの|か","September 9th"
"kanken-10","ももが九つ","も|も|が|ここの|つ","nine peaches"
"kanken-10","九人でやるスポーツ","きゅう|にん|で|や|る|す|ぽ|ー|つ","sport played by nine people"
"kanken-10","夏休み","なつ|やす|み","summer vacation"
"kanken-10","学校を休む","がっ|こう|を|やす|む","absent from school"
"kanken-10","休日はからだを休めよう","きゅう|じつ|は|か|ら|だ|を|やす|め|よ|う","let's rest our bodies on holidays"
"kanken-10","休みが四日つづく","やす|み|が|よっ|か|つ|づ|く","four days of holidays in a row"
"kanken-10","玉のり","たま|の|り","balancing on a ball"
"kanken-10","お年玉","お|とし|だま","New Year's monetary gift"
"kanken-10","シャボン玉をとばす","しゃ|ぼ|ん|だま|を|と|ば|す","blow soap bubbles"
"kanken-10","金づち","かな|づち","hammer"
"kanken-10","金メダル","きん|め|だ|る","gold medal"
"kanken-10","貯金ばこにお金をためる","ちょ|きん|ば|こ|に|お|かね|を|た|め|る","save money in a piggy bank"
"kanken-10","青空","あお|ぞら","blue sky"
"kanken-10","空きかん","あ|き|か|ん","empty can"
"kanken-10","空っぽ","か|ら|っ|ぽ","empty"
"kanken-10","月曜日","げつ|よう|び","Monday"
"kanken-10","正月","しょう|がつ","New Year"
"kanken-10","お月見をする","お|つき|み|を|す|る","view the moon"
"kanken-10","犬小屋","いぬ|ご|や","doghouse"
"kanken-10","番犬","ばん|けん","watchdog"
"kanken-10","犬の赤ちゃん","いぬ|の|あか|ちゃん","puppy"
"kanken-10","お見まい","お|み|ま|い","visit to a sick person"
"kanken-10","見学","けん|がく","field trip; observation"
"kanken-10","赤いやねが見える","あか|い|や|ね|が|み|え|る","can see a red roof"
"kanken-10","あめ玉が五つ","あ|め|だま|が|いつ|つ","five candy balls"
"kanken-10","五本のゆび","ご|ほん|の|ゆ|び","five fingers"
"kanken-10","五月五日はこどもの日","ご|がつ|い|つ|か|は|こ|ど|も|の|ひ","May 5th is Children's Day"
"kanken-10","出口","で|ぐち","exit"
"kanken-10","口ぶえをふく","くち|ぶ|え|を|ふ|く","whistle"
"kanken-10","せかいの人口","せ|か|い|の|じん|こう","world population"
"kanken-10","口を大きくあける","くち|を|おお|き|く|あ|け|る","open mouth wide"
"kanken-10","校庭","こう|てい","schoolyard"
"kanken-10","小学校","しょう|がっ|こう","elementary school"
"kanken-10","休校になる","きゅう|こう|に|な|る","school is closed"
"kanken-10","左足","ひだり|あし","left foot"
"kanken-10","左折する","さ|せつ|す|る","turn left"
"kanken-10","車は左がわをとおる","くるま|は|ひだり|が|わ|を|と|お|る","cars drive on the left side"
"kanken-10","三日月","み|か|づき","crescent moon"
"kanken-10","三輪車","さん|りん|しゃ","tricycle"
"kanken-10","三月三日はひなまつり","さん|がつ|みっ|か|は|ひ|な|ま|つ|り","March 3rd is the Doll Festival"
"kanken-10","山林","さん|りん","mountain forest"
"kanken-10","火山","か|ざん","volcano"
"kanken-10","山のぼりに出かける","やま|の|ぼ|り|に|で|か|け|る","go mountain climbing"
"kanken-10","親子","おや|こ","parent and child"
"kanken-10","男子と女子","だん|し|と|じょ|し","boys and girls"
"kanken-10","子どもたちがあそぶ","こ|ど|も|た|ち|が|あ|そ|ぶ","children play"
"kanken-10","ごご四時","ご|ご|よ|じ","4:00 PM"
"kanken-10","四角いまど","し|かく|い|ま|ど","square window"
"kanken-10","四足のくつ","よん|そく|の|く|つ","four pairs of shoes"
"kanken-10","糸でんわ","いと|でん|わ","string telephone"
"kanken-10","毛糸","け|いと","wool yarn"
"kanken-10","つり糸がからまる","つ|り|いと|が|か|ら|ま|る","fishing line gets tangled"
"kanken-10","漢字","かん|じ","kanji"
"kanken-10","数字","すう|じ","number; numeral"
"kanken-10","字を正しくかこう","じ|を|ただ|し|く|か|こ|う","let's write characters correctly"
"kanken-10","小さい字をよむ","ちい|さ|い|じ|を|よ|む","read small print"
"kanken-10","耳かざり","みみ|か|ざ|り","earring"
"kanken-10","耳鼻科","じ|び|か","otolaryngology (ENT)"
"kanken-10","耳をすます","みみ|を|す|ま|す","listen carefully"
"kanken-10","七色のにじ","なな|いろ|の|に|じ","seven-colored rainbow"
"kanken-10","ほしが七つ","ほ|し|が|なな|つ","seven stars"
"kanken-10","七月七日は七夕","しち|がつ|な|の|か|は|た|な|ば|た","July 7th is Tanabata"
"kanken-10","車庫","しゃ|こ","garage"
"kanken-10","水車","すい|しゃ","water wheel"
"kanken-10","車にのる","くるま|に|の|る","ride in a car"
"kanken-10","手がみ","て|がみ","letter"
"kanken-10","手綱","た|づな","bridle; reins"
"kanken-10","上手","じょう|ず","skillful"
"kanken-10","泳ぎが下手だ","およ|ぎ|が|へ|た|だ","poor at swimming"
"kanken-10","赤十字","せき|じゅう|じ","Red Cross"
"kanken-10","十円玉が十二こ","じゅう|えん|だま|が|じゅう|に|こ","twelve 10-yen coins"
"kanken-10","十月十日はうんどうかいだ","じゅう|がつ|とお|か|は|う|ん|ど|う|か|い|だ","October 10th is sports day"
"kanken-10","おもい出","お|も|い|で","memory"
"kanken-10","出発","しゅっ|ぱつ","departure"
"kanken-10","スピードを出す","す|ぴ|ー|ど|を|だ|す","speed up"
"kanken-10","女子","じょ|し","girl; woman"
"kanken-10","王女","おう|じょ","princess"
"kanken-10","女神","め|がみ","goddess"
"kanken-10","女の人が犬をだく","おんな|の|ひと|が|いぬ|を|だ|く","a woman hugs a dog"
"kanken-10","小石","こ|いし","pebble"
"kanken-10","小川","お|がわ","brook; stream"
"kanken-10","小学生","しょう|がく|せい","elementary school student"
"kanken-10","川上","かわ|かみ","upstream"
"kanken-10","上を見る","うえ|を|み|る","look up"
"kanken-10","屋上に上がる","おく|じょう|に|あ|が|る","go up to the rooftop"
"kanken-10","上りの電車","のぼ|り|の|でん|しゃ","inbound train (going to city)"
"kanken-10","森をさんぽする","もり|を|さ|ん|ぽ|す|る","stroll through the forest"
"kanken-10","森林","しん|りん","forest"
"kanken-10","つりの名人","つ|り|の|めい|じん","master of fishing"
"kanken-10","人形","にん|ぎょう","doll"
"kanken-10","大人","おと|な","adult"
"kanken-10","男の人が三人","おとこ|の|ひと|が|さん|にん","three men"
"kanken-10","水玉もよう","みず|たま|も|よ|う","polka dot pattern"
"kanken-10","水中めがね","すい|ちゅう|め|が|ね","swimming goggles"
"kanken-10","水道の水をためる","すい|どう|の|みず|を|た|め|る","save tap water"
"kanken-10","正方形","せい|ほう|けい","square"
"kanken-10","しせいを正す","し|せ|い|を|ただ|す","correct one's posture"
"kanken-10","正直にいう","しょう|じき|に|い|う","speak honestly"
"kanken-10","正しいこたえ","ただ|し|い|こ|た|え","correct answer"
"kanken-10","生たまご","なま|た|ま|ご","raw egg"
"kanken-10","たん生日","た|ん|じょう|び","birthday"
"kanken-10","子が生まれる","こ|が|う|ま|れ|る","a child is born"
"kanken-10","ひげを生やした先生","ひ|げ|を|は|や|し|た|せん|せい","a teacher with a beard"
"kanken-10","青虫","あお|むし","cabbage caterpillar"
"kanken-10","青年","せい|ねん","youth; young man"
"kanken-10","青いうみをながめる","あお|い|う|み|を|な|が|め|る","gaze at the blue sea"
"kanken-10","夕日","ゆう|ひ","setting sun"
"kanken-10","夕やけ","ゆう|や|け","sunset glow"
"kanken-10","七夕","たな|ばた","Star Festival"
"kanken-10","夕だちにあう","ゆう|だ|ち|に|あ|う","get caught in an evening shower"
"kanken-10","石油ストーブ","せき|ゆ|す|と|ー|ぶ","oil heater"
"kanken-10","じ石","じ|しゃく","magnet"
"kanken-10","円い石をひろう","まる|い|いし|を|ひ|ろ|う","pick up a round stone"
"kanken-10","赤ちゃん","あか|ちゃん","baby"
"kanken-10","赤飯","せき|はん","red bean rice"
"kanken-10","空が赤くそまる","そら|が|あか|く|そ|ま|る","sky turns red"
"kanken-10","千円さつ","せん|えん|さ|つ","thousand yen bill"
"kanken-10","千本ざくら","せん|ぼん|ざ|く|ら","a thousand cherry trees"
"kanken-10","千代がみでつるをおる","ち|よ|が|み|で|つ|る|を|お|る","fold a crane with colored paper"
"kanken-10","川下り","かわ|くだ|り","going down a river"
"kanken-10","天の川","あま|の|がわ","Milky Way"
"kanken-10","河川","か|せん","rivers"
"kanken-10","川むこうの村にすむ","かわ|む|こ|う|の|むら|に|す|む","live in the village across the river"
"kanken-10","つま先","つ|ま|さき","tiptoe"
"kanken-10","先月","せん|げつ","last month"
"kanken-10","先をあらそう","さき|を|あ|ら|そ|う","compete to be first"
"kanken-10","早足","はや|あし","fast walking"
"kanken-10","早朝れんしゅう","そう|ちょう|れ|ん|しゅ|う","early morning practice"
"kanken-10","早めに学校へいく","はや|め|に|がっ|こう|へ|い|く","go to school early"
"kanken-10","草むら","くさ|む|ら","grassy place"
"kanken-10","草原","そう|げん","grassland; meadow"
"kanken-10","田んぼの草とりをする","た|ん|ぼ|の|くさ|と|り|を|す|る","weed the rice field"
"kanken-10","足くび","あし|く|び","ankle"
"kanken-10","遠足","えん|そく","excursion"
"kanken-10","力が足りない","ちから|が|た|り|な|い","insufficient strength"
"kanken-10","村まつり","むら|ま|つ|り","village festival"
"kanken-10","市町村","し|ちょう|そん","cities, towns, and villages"
"kanken-10","となり村の村長さん","と|な|り|むら|の|そん|ちょう|さ|ん","the village headman of the neighboring village"
"kanken-10","大男","おお|おとこ","giant man"
"kanken-10","大学生","だい|がく|せい","university student"
"kanken-10","マラソン大会","ま|ら|そ|ん|たい|かい","marathon tournament"
"kanken-10","男女","だん|じょ","men and women"
"kanken-10","長男","ちょう|なん","eldest son"
"kanken-10","男の子がねむっている","おとこ|の|こ|が|ね|む|っ|て|い|る","the boy is sleeping"
"kanken-10","竹とんぼ","たけ|と|ん|ぼ","bamboo dragonfly (toy)"
"kanken-10","竹林","ちく|りん","bamboo grove"
"kanken-10","竹うまにのる","たけ|う|ま|に|の|る","walk on stilts"
"kanken-10","中ゆび","なか|ゆ|び","middle finger"
"kanken-10","空中","くう|ちゅう","mid-air"
"kanken-10","一日中","いち|にち|じゅう","all day long"
"kanken-10","ポケットの中を見る","ぽ|け|っ|と|の|なか|を|み|る","look inside the pocket"
"kanken-10","虫歯","むし|ば","cavity"
"kanken-10","かぶと虫","か|ぶ|と|むし","rhinoceros beetle"
"kanken-10","こん虫をかんさつする","こ|ん|ちゅう|を|か|ん|さ|つ|す|る","observe insects"
"kanken-10","町はずれ","まち|は|ず|れ","outskirts of town"
"kanken-10","下町","した|まち","downtown; old town"
"kanken-10","町内のおみこしが出る","ちょう|ない|の|お|み|こ|し|が|で|る","the neighborhood portable shrine comes out"
"kanken-10","天国","てん|ごく","heaven"
"kanken-10","天ぷら","てん|ぷ|ら","tempura"
"kanken-10","天の川がきれいだ","あま|の|がわ|が|き|れ|い|だ","the Milky Way is beautiful"
"kanken-10","水田","すい|でん","rice paddy"
"kanken-10","田園ふうけい","でん|えん|ふ|う|け|い","rural landscape"
"kanken-10","田んぼに水をひく","た|ん|ぼ|に|みず|を|ひ|く","draw water into the rice field"
"kanken-10","土あそび","つち|あ|そ|び","playing in the dirt"
"kanken-10","土地","と|ち","land"
"kanken-10","ねん土で犬をつくる","ね|ん|ど|で|いぬ|を|つ|く|る","make a dog out of clay"
"kanken-10","二年生","に|ねん|せい","second grade student"
"kanken-10","二月二日","に|がつ|ふつ|か","February 2nd"
"kanken-10","二十日","はつ|か","20th day of the month"
"kanken-10","二人","ふた|り","two people"
"kanken-10","クッキーを二つにわる","く|っ|き|ー|を|ふた|つ|に|わ|る","break a cookie in two"
"kanken-10","日やけ","ひ|や|け","sunburn"
"kanken-10","休日","きゅう|じつ","holiday"
"kanken-10","十日は日曜日だ","とお|か|は|にち|よう|び|だ","the 10th is a Sunday"
"kanken-10","手入れ","て|い|れ","maintenance; care"
"kanken-10","立ち入りきんし","た|ち|い|り|き|ん|し","no entry"
"kanken-10","入場けんをもって入る","にゅう|じょう|け|ん|を|も|っ|て|は|い|る","enter with an admission ticket"
"kanken-10","うえ木の手入れをする","う|え|き|の|て|い|れ|を|す|る","prune the garden plants"
"kanken-10","お年より","お|とし|よ|り","elderly person"
"kanken-10","一年間","いち|ねん|かん","one year period"
"kanken-10","あねは二つ年上だ","あ|ね|は|ふた|つ|とし|うえ|だ","my older sister is two years older"
"kanken-10","白さぎ","しら|さ|ぎ","white egret"
"kanken-10","まっ白な白鳥","ま|っ|しろ|な|はく|ちょう","pure white swan"
"kanken-10","白いくもがうかぶ","しろ|い|く|も|が|う|か|ぶ","white clouds float"
"kanken-10","八えざくら","や|え|ざ|く|ら","double-flowered cherry blossom"
"kanken-10","八月八日","はち|がつ|よう|か","August 8th"
"kanken-10","りんごを八つにきる","り|ん|ご|を|やっ|つ|に|き|る","cut an apple into eight pieces"
"kanken-10","百科じてん","ひゃっ|か|じ|て|ん","encyclopedia"
"kanken-10","百点をとる","ひゃく|てん|を|と|る","get a perfect score (100 points)"
"kanken-10","百さいのおばあさん","ひゃく|さ|い|の|お|ば|あ|さ|ん","100-year-old grandmother"
"kanken-10","作文","さく|ぶん","composition; writing"
"kanken-10","天文台","てん|もん|だい","observatory"
"kanken-10","十一月三日は文化の日","じゅう|いち|がつ|みっ|か|は|ぶん|か|の|ひ","November 3rd is Culture Day"
"kanken-10","木かげ","こ|か|げ","shade of a tree"
"kanken-10","大木","たい|ぼく","large tree"
"kanken-10","木曜日","もく|よう|び","Thursday"
"kanken-10","木の下にこしを下ろす","き|の|した|に|こ|し|を|お|ろ|す","sit down under a tree"
"kanken-10","本気","ほん|き","seriousness"
"kanken-10","手本","て|ほん","model; example"
"kanken-10","ろうそくを一本立てる","ろ|う|そ|く|を|いっ|ぽん|た|て|る","set up one candle"
"kanken-10","名前","な|まえ","name"
"kanken-10","名字","みょう|じ","surname"
"kanken-10","有名になる","ゆう|めい|に|な|る","become famous"
"kanken-10","目ざましどけい","め|ざ|ま|し|ど|け|い","alarm clock"
"kanken-10","目標","もく|ひょう","goal; objective"
"kanken-10","くものきれ目","く|も|の|き|れ|め","break in the clouds"
"kanken-10","立ち上がる","た|ち|あ|が|る","stand up"
"kanken-10","起立","き|りつ","stand up (command)"
"kanken-10","板を立てる","い|た|を|た|て|る","stand a board up"
"kanken-10","努力","ど|りょく","effort"
"kanken-10","力作","りき|さく","masterpiece"
"kanken-10","力いっぱい走る","ちから|い|っ|ぱ|い|は|し|る","run with all one's might"
"kanken-10","ぞう木林","ぞう|き|ばやし","thicket; copse"
"kanken-10","林道","りん|どう","woodland path"
"kanken-10","林の中をあるく","はやし|の|なか|を|あ|る|く","walk in the woods"
"kanken-10","六つぎりのパン","む|っ|つ|ぎ|り|の|ぱ|ん","bread cut into six slices"
"kanken-10","くりが六つ","く|り|が|む|っ|つ","six chestnuts"
"kanken-10","たん生日は六月六日だ","た|ん|じょう|び|は|ろ|く|がつ|む|い|か|だ","birthday is June 6th"`;

var kanken9 = `"tags","kanji","readings","definition"
"kanken-9","引力","いん|りょく","gravity"
"kanken-9","つな引き","つな|ひ|き","tug of war"
"kanken-9","引き算","ひ|き|ざん","subtraction"
"kanken-9","遠くに引っこす","とお|く|に|ひ|っ|こ|す","move far away"
"kanken-9","羽毛","う|もう","feathers"
"kanken-9","羽子板","は|ご|いた","battledore"
"kanken-9","白い羽","しろ|い|はね","white feather"
"kanken-9","あひるが三羽いる","あひるが|さん|ば|いる","three ducks"
"kanken-9","雲海","うん|かい","sea of clouds"
"kanken-9","入道雲","にゅう|どう|ぐも","cumulonimbus cloud"
"kanken-9","今夜は空に雲がない","こん|や|は|そら|に|くも|が|ない","no clouds tonight"
"kanken-9","遊園地","ゆう|えん|ち","amusement park"
"kanken-9","花園","はな|ぞの","flower garden"
"kanken-9","どうぶつ園に行こう","どうぶつ|えん|に|い|こう","go to zoo"
"kanken-9","遠足","えん|そく","excursion"
"kanken-9","久遠","く|おん","eternity"
"kanken-9","遠い山","とお|い|やま","distant mountain"
"kanken-9","遠あさの海であそぶ","とお|あさ|の|うみ|で|あそぶ","play in shallow sea"
"kanken-9","幾何学","き|か|がく","geometry"
"kanken-9","何回","なん|かい","how many times"
"kanken-9","今日は何曜日？","きょう|は|なん|よう|び|？","what day is it"
"kanken-9","おやつは何かな？","おやつは|なに|かな|？","what is snack"
"kanken-9","科学","か|がく","science"
"kanken-9","生活科","せい|かつ|か","living environment studies"
"kanken-9","教科書を読む","きょう|か|しょ|を|よ|む","read textbook"
"kanken-9","初夏","しょ|か","early summer"
"kanken-9","夏至","げ|し","summer solstice"
"kanken-9","夏休み","なつ|やす|み","summer vacation"
"kanken-9","夏が近づく","なつ|が|ちか|づく","summer approaches"
"kanken-9","家族","か|ぞく","family"
"kanken-9","家来","け|らい","servant"
"kanken-9","となりの家","となり|の|いえ","neighbor's house"
"kanken-9","いっけん家にすむ","いっけん|や|に|す|む","live in detached house"
"kanken-9","歌手","か|しゅ","singer"
"kanken-9","校歌","こう|か","school song"
"kanken-9","歌声","うた|ごえ","singing voice"
"kanken-9","大きな声で歌う","おお|きな|こえ|で|うた|う","sing loudly"
"kanken-9","画用紙","が|よう|し","drawing paper"
"kanken-9","計画","けい|かく","plan"
"kanken-9","画家をめざす","が|か|を|めざす","aim to be painter"
"kanken-9","後回し","あと|まわ|し","postpone"
"kanken-9","歩き回る","ある|き|まわ|る","walk around"
"kanken-9","船にのるのは二回目だ","ふね|に|のる|の|は|に|かい|め|だ","second time on boat"
"kanken-9","会社","かい|しゃ","company"
"kanken-9","音楽会","おん|がく|かい","concert"
"kanken-9","会釈","え|しゃく","nod"
"kanken-9","友だちに会う","とも|だち|に|あ|う","meet friend"
"kanken-9","海岸","かい|がん","coast"
"kanken-9","青い海","あお|い|うみ","blue sea"
"kanken-9","海の水はからい","うみ|の|みず|は|からい","sea water is salty"
"kanken-9","絵画","かい|が","painting"
"kanken-9","絵本","え|ほん","picture book"
"kanken-9","絵日記","え|にっ|き","picture diary"
"kanken-9","絵はがきを買う","え|はがき|を|か|う","buy postcard"
"kanken-9","外国","がい|こく","foreign country"
"kanken-9","外科","げ|か","surgery"
"kanken-9","おには外","おに|は|そと","demons out"
"kanken-9","ボタンを外す","ぼたん|を|はず|す","unbutton"
"kanken-9","三角","さん|かく","triangle"
"kanken-9","まがり角","まがり|かど","corner"
"kanken-9","牛の角","うし|の|つの","bull horn"
"kanken-9","つぎの角をまがる","つぎ|の|かど|を|まがる","turn at corner"
"kanken-9","音楽会","おん|がく|かい","concert"
"kanken-9","楽園","らく|えん","paradise"
"kanken-9","楽しいゆめ","たの|しい|ゆめ","pleasant dream"
"kanken-9","スキーを楽しむ","すきー|を|たの|しむ","enjoy skiing"
"kanken-9","活動","かつ|どう","activity"
"kanken-9","活火山","かっ|か|ざん","active volcano"
"kanken-9","リレーで活やくする","りれー|で|かつ|やく|する","active in relay"
"kanken-9","時間","じ|かん","time"
"kanken-9","世間","せ|けん","society"
"kanken-9","休みの間","やす|み|の|あいだ","during break"
"kanken-9","客間","きゃく|ま","guest room"
"kanken-9","仲間をあつめる","なか|ま|を|あつめる","gather friends"
"kanken-9","丸薬","がん|やく","pill"
"kanken-9","丸太","まる|た","log"
"kanken-9","丸い石","まる|い|いし","round stone"
"kanken-9","目を丸くする","め|を|まる|く|する","stare in amazement"
"kanken-9","岩石","がん|せき","rock"
"kanken-9","火山岩","か|ざん|がん","volcanic rock"
"kanken-9","岩場","いわ|ば","rocky place"
"kanken-9","岩になみが当たる","いわ|に|なみ|が|あたる","waves hit rocks"
"kanken-9","顔面","がん|めん","face"
"kanken-9","横顔","よこ|がお","profile"
"kanken-9","顔つき","かお|つき","look"
"kanken-9","顔をあらう","かお|を|あらう","wash face"
"kanken-9","汽車","き|しゃ","steam train"
"kanken-9","汽船","き|せん","steamship"
"kanken-9","汽笛","き|てき","whistle"
"kanken-9","船が汽笛を鳴らす","ふね|が|き|てき|を|な|らす","ship whistles"
"kanken-9","記録","き|ろく","record"
"kanken-9","筆記用具","ひっ|き|よう|ぐ","writing utensils"
"kanken-9","日記","にっ|き","diary"
"kanken-9","思い出を日記に記す","おも|いで|を|にっ|き|に|しる|す","write memories"
"kanken-9","帰国","き|こく","return country"
"kanken-9","帰り道","かえ|り|みち","way home"
"kanken-9","家に帰る","いえ|に|かえ|る","go home"
"kanken-9","弓道","きゅう|どう","archery"
"kanken-9","弓形","ゆみ|なり","arch shape"
"kanken-9","弓と矢","ゆみ|と|や","bow and arrow"
"kanken-9","弓を引く","ゆみ|を|ひ|く","draw bow"
"kanken-9","牛肉","ぎゅう|にく","beef"
"kanken-9","牛小屋","うし|ご|や","cowshed"
"kanken-9","牛のちちをしぼる","うし|の|ちち|を|しぼる","milk cow"
"kanken-9","金魚","きん|ぎょ","goldfish"
"kanken-9","魚市場","うお|いち|ば","fish market"
"kanken-9","魚つり","さかな|つり","fishing"
"kanken-9","小魚を丸ごと食べる","こ|ざかな|を|まる|ごと|たべる","eat small fish whole"
"kanken-9","上京","じょう|きょう","go to Tokyo"
"kanken-9","京浜工業地帯","けい|ひん|こう|ぎょう|ち|たい","Keihin industrial zone"
"kanken-9","東京タワー","とう|きょう|たわー","Tokyo Tower"
"kanken-9","おばが上京する","おば|が|じょう|きょう|する","aunt comes to Tokyo"
"kanken-9","勉強","べん|きょう","study"
"kanken-9","強引","ごう|いん","pushy"
"kanken-9","強い風","つよ|い|かぜ","strong wind"
"kanken-9","無理強い","む|り|じ|い","coercion"
"kanken-9","火を強める","ひ|を|つよ|める","strengthen fire"
"kanken-9","教室","きょう|しつ","classroom"
"kanken-9","説教","せっ|きょう","scolding"
"kanken-9","道を教える","みち|を|おし|える","teach way"
"kanken-9","先生から教わる","せん|せい|から|おそ|わる","learn from teacher"
"kanken-9","近所","きん|じょ","neighborhood"
"kanken-9","最近","さい|きん","recently"
"kanken-9","近道","ちか|みち","shortcut"
"kanken-9","近くの山にのぼる","ちか|く|の|やま|に|のぼる","climb nearby mountain"
"kanken-9","父兄","ふ|けい","guardians"
"kanken-9","兄さん","にい|さん","older brother"
"kanken-9","兄弟","きょう|だい","siblings"
"kanken-9","兄は高校生だ","あに|は|こう|こう|せい|だ","brother is high schooler"
"kanken-9","図形","ず|けい","figure"
"kanken-9","人形","にん|ぎょう","doll"
"kanken-9","母の形見","はは|の|かた|み","keepsake"
"kanken-9","顔の形","かお|の|かたち","face shape"
"kanken-9","ニンジンをひし形に切る","にんじん|を|ひし|がた|に|き|る","cut carrot diamond"
"kanken-9","計画","けい|かく","plan"
"kanken-9","合計","ごう|けい","sum"
"kanken-9","時間を計る","じ|かん|を|はか|る","measure time"
"kanken-9","計算のテストをうける","けい|さん|の|てすと|を|うける","take calc test"
"kanken-9","元気","げん|き","healthy"
"kanken-9","元日","がん|じつ","New Year's Day"
"kanken-9","火の元","ひ|の|もと","source of fire"
"kanken-9","おもちゃを元にもどす","おもちゃ|を|もと|に|もどす","return toy"
"kanken-9","言葉","こと|ば","word"
"kanken-9","伝言","でん|ごん","message"
"kanken-9","発言","はつ|げん","speech"
"kanken-9","わがままを言う","わがまま|を|い|う","say selfish things"
"kanken-9","原子力","げん|し|りょく","nuclear power"
"kanken-9","川原","かわ|ら","riverbank"
"kanken-9","野原","の|はら","field"
"kanken-9","高原で休日をすごす","こう|げん|で|きゅう|じつ|を|すごす","holiday in highlands"
"kanken-9","一戸だての家","いっ|こ|だて|の|いえ","detached house"
"kanken-9","戸じまり","と|じまり","lock up"
"kanken-9","雨戸","あま|ど","shutter"
"kanken-9","戸をしめる","と|を|しめる","close door"
"kanken-9","古本","ふる|ほん","used book"
"kanken-9","中古車","ちゅう|こ|しゃ","used car"
"kanken-9","古い家","ふる|い|いえ","old house"
"kanken-9","古い新聞をかたづける","ふる|い|しん|ぶん|を|かたづける","clean old newspapers"
"kanken-9","午前","ご|ぜん","AM"
"kanken-9","正午","しょう|ご","noon"
"kanken-9","午後","ご|ご","PM"
"kanken-9","テストは正午におわった","てすと|は|しょう|ご|に|おわった","test ended at noon"
"kanken-9","食後","しょく|ご","after meal"
"kanken-9","気後れ","き|おく|れ","diffident"
"kanken-9","後しまつ","あと|しまつ","cleanup"
"kanken-9","父の後ろについていく","ちち|の|うし|ろ|に|ついていく","follow father"
"kanken-9","語学","ご|がく","language study"
"kanken-9","外国語","がい|こく|ご","foreign language"
"kanken-9","語り手","かた|り|て","narrator"
"kanken-9","ゆめを語り合う","ゆめ|を|かた|り|あ|う","talk dreams"
"kanken-9","工作","こう|さく","handicraft"
"kanken-9","図工","ず|こう","arts and crafts"
"kanken-9","大工さん","だい|く|さん","carpenter"
"kanken-9","工場を見学する","こう|じょう|を|けん|がく|する","visit factory"
"kanken-9","公園","こう|えん","park"
"kanken-9","主人公","しゅ|じん|こう","protagonist"
"kanken-9","公の場","おおやけ|の|ば","public place"
"kanken-9","公平に分ける","こう|へい|に|わける","divide fairly"
"kanken-9","広告","こう|こく","ad"
"kanken-9","広場","ひろ|ば","plaza"
"kanken-9","広い野原","ひろ|い|の|はら","wide field"
"kanken-9","麦ばたけが広がる","むぎ|ばたけ|が|ひろ|がる","wheat field spreads"
"kanken-9","交番","こう|ばん","police box"
"kanken-9","道が交わる","みち|が|まじ|わる","roads cross"
"kanken-9","鳥が飛び交う","とり|が|と|び|か|う","birds fly"
"kanken-9","交通がべんりになる","こう|つう|が|べん|り|に|なる","transport convenient"
"kanken-9","光線","こう|せん","beam"
"kanken-9","日光","にっ|こう","sunlight"
"kanken-9","月の光","つき|の|ひかり","moonlight"
"kanken-9","川の水がきらきら光る","かわ|の|みず|が|きらきら|ひか|る","water sparkles"
"kanken-9","参考書","さん|こう|しょ","reference book"
"kanken-9","考え方","かんが|え|かた","way of thinking"
"kanken-9","インコの名前を考える","いんこ|の|な|まえ|を|かんが|える","think name"
"kanken-9","旅行","りょ|こう","travel"
"kanken-9","行列","ぎょう|れつ","procession"
"kanken-9","東京に行く","とう|きょう|に|い|く","go to Tokyo"
"kanken-9","大会が行われる","たい|かい|が|おこな|われる","tournament held"
"kanken-9","高原","こう|げん","highlands"
"kanken-9","高級品","こう|きゅう|ひん","luxury goods"
"kanken-9","高い山","たか|い|やま","high mountain"
"kanken-9","高いビルがならぶ","たか|い|びる|が|ならぶ","tall buildings"
"kanken-9","黄金","おう|ごん","gold"
"kanken-9","黄色","き|いろ","yellow"
"kanken-9","たまごの黄身","たまご|の|き|み","yolk"
"kanken-9","黄色いリボンをむすぶ","き|いろ|い|りぼん|を|むすぶ","tie yellow ribbon"
"kanken-9","合計","ごう|けい","sum"
"kanken-9","合宿","がっ|しゅく","camp"
"kanken-9","合図","あい|ず","signal"
"kanken-9","声を合わせる","こえ|を|あ|わせる","unison"
"kanken-9","おやつを分け合う","おやつ|を|わ|け|あ|う","share snacks"
"kanken-9","峡谷","きょう|こく","canyon"
"kanken-9","谷間","たに|ま","valley"
"kanken-9","谷川","たに|がわ","stream"
"kanken-9","谷にそった道を歩く","たに|に|そった|みち|を|あるく","walk valley path"
"kanken-9","国土","こく|ど","territory"
"kanken-9","南国","なん|ごく","southern land"
"kanken-9","雪国","ゆき|ぐに","snow country"
"kanken-9","トラックが国道を走る","とらっく|が|こく|どう|を|はしる","truck on highway"
"kanken-9","黒板","こく|ばん","blackboard"
"kanken-9","大黒柱","だい|こく|ばしら","mainstay"
"kanken-9","黒い雲","くろ|い|くも","black cloud"
"kanken-9","店の前は黒山の人だかりだ","みせ|の|まえ|は|くろ|やま|の|ひと|だかり|だ","crowd at shop"
"kanken-9","今夜","こん|や","tonight"
"kanken-9","ただ今","ただ|いま","now/I'm home"
"kanken-9","今朝","け|さ","this morning"
"kanken-9","今年","こ|とし","this year"
"kanken-9","今日は雨がふるそうだ","きょう|は|あめ|が|ふる|そう|だ","rain likely today"
"kanken-9","天才","てん|さい","genius"
"kanken-9","英才教育","えい|さい|きょう|いく","gifted ed"
"kanken-9","音楽の才能をのばす","おん|がく|の|さい|のう|を|のばす","develop talent"
"kanken-9","細心のちゅうい","さい|しん|の|ちゅうい","meticulous"
"kanken-9","細い糸","ほそ|い|いと","thin thread"
"kanken-9","細かい字","こま|かい|じ","small char"
"kanken-9","細長い石をひろう","ほそ|なが|い|いし|を|ひろう","pick long stone"
"kanken-9","作文","さく|ぶん","composition"
"kanken-9","工作","こう|さく","handicraft"
"kanken-9","作業","さ|ぎょう","work"
"kanken-9","動作","どう|さ","action"
"kanken-9","人形を作る","にん|ぎょう|を|つく|る","make doll"
"kanken-9","算数","さん|すう","math"
"kanken-9","計算","けい|さん","calc"
"kanken-9","暗算がとくいだ","あん|ざん|が|とくい|だ","good at mental math"
"kanken-9","中止","ちゅう|し","cancel"
"kanken-9","通行止め","つう|こう|ど|め","closed"
"kanken-9","わらいが止まらない","わらい|が|と|まらない","cant stop laughing"
"kanken-9","市長","し|ちょう","mayor"
"kanken-9","都市","と|し","city"
"kanken-9","朝市","あさ|いち","morning market"
"kanken-9","市内を観光する","し|ない|を|かん|こう|する","sightsee city"
"kanken-9","矢印","や|じるし","arrow"
"kanken-9","矢車","や|ぐるま","arrow wheel"
"kanken-9","こいのぼりの矢車","こいのぼり|の|や|ぐるま","carp streamer wheel"
"kanken-9","矢をいる","や|を|い|る","shoot arrow"
"kanken-9","姉妹","し|まい","sisters"
"kanken-9","姉さん","ねえ|さん","sister"
"kanken-9","姉と歩く","あね|と|あるく","walk with sister"
"kanken-9","思案にくれる","し|あん|に|くれる","lost in thought"
"kanken-9","思い出","おも|いで","memory"
"kanken-9","午後からは雨だと思う","ご|ご|から|は|あめ|だ|と|おも|う","think rain later"
"kanken-9","半紙","はん|し","calligraphy paper"
"kanken-9","手紙","て|がみ","letter"
"kanken-9","紙ひこうき","かみ|ひこうき","paper plane"
"kanken-9","手紙を書く","て|がみ|を|か|く","write letter"
"kanken-9","寺社","じ|しゃ","temples/shrines"
"kanken-9","お寺まいり","お|てら|まいり","visit temple"
"kanken-9","寺でひと休みする","てら|で|ひと|やす|み|する","rest at temple"
"kanken-9","大自然","だい|し|ぜん","nature"
"kanken-9","自転車","じ|てん|しゃ","bicycle"
"kanken-9","自信をもつ","じ|しん|を|もつ","confidence"
"kanken-9","自らの力で勝つ","みずか|ら|の|ちから|で|かつ","win by self"
"kanken-9","時報","じ|ほう","time signal"
"kanken-9","三時のおやつ","さん|じ|の|おやつ","3pm snack"
"kanken-9","一年生の時の写真","いち|ねん|せい|の|とき|の|しゃ|しん","1st grade photo"
"kanken-9","時計","と|けい","clock"
"kanken-9","時間がたつのをわすれる","じ|かん|が|たつ|の|を|わすれる","forget time"
"kanken-9","室内","しつ|ない","indoor"
"kanken-9","地下室","ち|か|しつ","basement"
"kanken-9","室町時代","むろ|まち|じ|だい","Muromachi"
"kanken-9","水泳教室に通う","すい|えい|きょう|しつ|に|かよ|う","swim class"
"kanken-9","社長","しゃ|ちょう","president"
"kanken-9","会社","かい|しゃ","company"
"kanken-9","お社","お|やしろ","shrine"
"kanken-9","神社にまいる","じん|じゃ|に|まいる","visit shrine"
"kanken-9","弱点","じゃく|てん","weakness"
"kanken-9","強弱をつける","きょう|じゃく|を|つける","vary strength"
"kanken-9","ひなが弱る","ひな|が|よわ|る","chick weakens"
"kanken-9","ガスの火を弱める","がす|の|ひ|を|よわ|める","weaken fire"
"kanken-9","首位","しゅ|い","top"
"kanken-9","長い首","なが|い|くび","long neck"
"kanken-9","ダイヤの首かざりを見る","だいや|の|くび|かざり|を|みる","diamond necklace"
"kanken-9","秋分の日","しゅう|ぶん|の|ひ","Autumn Equinox"
"kanken-9","読書の秋","どく|しょ|の|あき","reading autumn"
"kanken-9","秋の夕べに虫が鳴く","あき|の|ゆう|べ|に|むし|が|な|く","insects chirp"
"kanken-9","週末","しゅう|まつ","weekend"
"kanken-9","一週間","いっ|しゅう|かん","one week"
"kanken-9","来週のよていを立てる","らい|しゅう|の|よてい|を|たてる","plan next week"
"kanken-9","春分の日","しゅん|ぶん|の|ひ","Spring Equinox"
"kanken-9","春休み","はる|やす|み","spring break"
"kanken-9","春の野原を歩く","はる|の|の|はら|を|あるく","walk spring field"
"kanken-9","書店","しょ|てん","bookstore"
"kanken-9","教科書","教科書",""
"kanken-9","日記を書く","にっ|き|を|か|く","write diary"
"kanken-9","少女","しょう|じょ","girl"
"kanken-9","多少","た|しょう","somewhat"
"kanken-9","少しだけ食べる","すこ|し|だけ|たべる","eat little"
"kanken-9","今年の冬は雪が少ない","こ|とし|の|ふゆ|は|ゆき|が|すく|ない","little snow"
"kanken-9","場所","ば|しょ","place"
"kanken-9","広場","ひろ|ば","plaza"
"kanken-9","運動場","うん|どう|じょう","playground"
"kanken-9","大会に出場する","たい|かい|に|しゅつ|じょう|する","participate"
"kanken-9","色紙","しき|し","colored paper"
"kanken-9","十二色のクレヨン","じゅう|に|しょく|の|くれよん","12 crayons"
"kanken-9","色えんぴつ","いろ|えんぴつ","colored pencil"
"kanken-9","黄色い風船を買う","き|いろ|い|ふう|せん|を|か|う","buy yellow balloon"
"kanken-9","食塩","しょく|えん","salt"
"kanken-9","夕食","ゆう|しょく","dinner"
"kanken-9","断食","だん|じき","fasting"
"kanken-9","のみ食い","のみ|く|い","eat drink"
"kanken-9","面食らう","めん|く|らう","confused"
"kanken-9","ごはんを食べる","ごはん|を|た|べる","eat rice"
"kanken-9","心配","しん|ぱい","worry"
"kanken-9","用心","よう|じん","caution"
"kanken-9","やさしい心","やさしい|こころ","kind heart"
"kanken-9","明日の天気を心配する","あした|の|てん|き|を|しん|ぱい|する","worry weather"
"kanken-9","新入生","しん|にゅう|せい","new student"
"kanken-9","最新のゲーム","さい|しん|の|げーむ","latest game"
"kanken-9","新しいくつ","あたら|しい|くつ","new shoes"
"kanken-9","新妻","にい|づま","new wife"
"kanken-9","思いを新たにする","おも|い|を|あら|た|に|する","renew resolve"
"kanken-9","親切","しん|せつ","kindness"
"kanken-9","両親","りょう|しん","parents"
"kanken-9","親子","おや|こ","parent child"
"kanken-9","親しい友だち","した|しい|とも|だち","close friend"
"kanken-9","読書に親しむ","どく|しょ|に|した|しむ","enjoy reading"
"kanken-9","図工","ず|こう","arts and crafts"
"kanken-9","地図","ち|ず","map"
"kanken-9","図書館","と|しょ|かん","library"
"kanken-9","合図をきめる","あい|ず|を|きめる","decide signal"
"kanken-9","学力向上を図る","がく|りょく|こう|じょう|を|はか|る","improve ability"
"kanken-9","数字","すう|じ","number"
"kanken-9","数奇屋づくり","す|き|や|づくり","sukiya style"
"kanken-9","数え歌","かぞ|え|うた","counting song"
"kanken-9","百まで数える","ひゃく|まで|かぞ|える","count to 100"
"kanken-9","関西","かん|さい","Kansai"
"kanken-9","西洋","せい|よう","West"
"kanken-9","夕日が西にしずむ","ゆう|ひ|が|にし|に|しずむ","sun sets west"
"kanken-9","声量","せい|りょう","volume"
"kanken-9","大音声","だい|おん|じょう","loud voice"
"kanken-9","歌声","うた|ごえ","singing voice"
"kanken-9","声色","こわ|いろ","tone"
"kanken-9","小鳥の鳴き声を聞く","こ|とり|の|な|き|ごえ|を|きく","hear bird"
"kanken-9","人工衛星","じん|こう|えい|せい","satellite"
"kanken-9","土星","ど|せい","Saturn"
"kanken-9","明星","みょう|じょう","star"
"kanken-9","流れ星","なが|れ|ぼし","shooting star"
"kanken-9","星空を見上げる","ほし|ぞら|を|み|あげる","look at stars"
"kanken-9","晴天","せい|てん","fine weather"
"kanken-9","快晴","かい|せい","clear weather"
"kanken-9","見晴らし台","み|は|らし|だい","view point"
"kanken-9","これは正月の晴れ着だ","これ|は|しょう|がつ|の|は|れ|ぎ|だ","New Year clothes"
"kanken-9","大切","たい|せつ","important"
"kanken-9","一切","いっ|さい","all"
"kanken-9","切手","きっ|て","stamp"
"kanken-9","二つに切る","ふた|つ|に|き|る","cut in two"
"kanken-9","雲の切れ間から月が見える","くも|の|き|れ|ま|から|つき|が|みえる","moon break clouds"
"kanken-9","積雪","せき|せつ","snowpack"
"kanken-9","雪国","ゆき|ぐに","snow country"
"kanken-9","雪だるまを作る","ゆき|だるま|を|つく|る","make snowman"
"kanken-9","船長","せん|ちょう","captain"
"kanken-9","風船","ふう|せん","balloon"
"kanken-9","船のり","ふな|のり","sailor"
"kanken-9","船がみなとに入る","ふね|が|みなと|に|はいる","ship enters port"
"kanken-9","線路","せん|ろ","rail"
"kanken-9","電線","でん|せん","wire"
"kanken-9","線を引く","せん|を|ひく","draw line"
"kanken-9","新幹線にのる","しん|かん|せん|に|のる","shinkansen"
"kanken-9","前後左右","ぜん|ご|さ|ゆう","directions"
"kanken-9","午前中","ご|ぜん|ちゅう","morning"
"kanken-9","名前","な|まえ","name"
"kanken-9","前へ進む","まえ|へ|すすむ","go forward"
"kanken-9","組織","そ|しき","org"
"kanken-9","二年三組","に|ねん|さん|くみ","2-3"
"kanken-9","テレビ番組","てれび|ばん|ぐみ","tv show"
"kanken-9","うでを組む","うで|を|く|む","cross arms"
"kanken-9","競走","きょう|そう","race"
"kanken-9","走者","そう|しゃ","runner"
"kanken-9","馬が走る","うま|が|はし|る","horse runs"
"kanken-9","多少","た|しょう","somewhat"
"kanken-9","人が多い","ひと|が|おお|い","many people"
"kanken-9","多数決をとる","た|すう|けつ|を|とる","majority vote"
"kanken-9","丸太","まる|た","log"
"kanken-9","太陽","たい|よう","sun"
"kanken-9","せきとりのうでは太い","せきとり|の|うで|は|ふと|い","sumo arm thick"
"kanken-9","体力","たい|りょく","stamina"
"kanken-9","体育","たい|いく","PE"
"kanken-9","体裁","てい|さい","appearance"
"kanken-9","体をきたえる","からだ|を|きたえる","train body"
"kanken-9","天文台","てん|もん|だい","observatory"
"kanken-9","台風","たい|ふう","typhoon"
"kanken-9","すべり台であそぶ","すべり|だい|で|あそぶ","slide"
"kanken-9","地下鉄","ち|か|てつ","subway"
"kanken-9","地面","じ|めん","ground"
"kanken-9","遊園地に行く","ゆう|えん|ち|に|い|く","go to park"
"kanken-9","電池","でん|ち","battery"
"kanken-9","大きな池","おお|きな|いけ","big pond"
"kanken-9","池の魚にえさをやる","いけ|の|さかな|に|えさ|を|やる","feed fish"
"kanken-9","知識","ち|しき","knowledge"
"kanken-9","未知","み|ち","unknown"
"kanken-9","もの知り","もの|し|り","know-it-all"
"kanken-9","きけんを知らせる","きけん|を|しら|せる","warn danger"
"kanken-9","茶わん","ちゃ|わん","bowl"
"kanken-9","麦茶","むぎ|ちゃ","barley tea"
"kanken-9","お茶をいれる","お|ちゃ|を|いれる","make tea"
"kanken-9","喫茶","きっ|さ","cafe"
"kanken-9","昼食","ちゅう|しょく","lunch"
"kanken-9","昼休み","ひる|やす|み","lunch break"
"kanken-9","昼食の時間","ちゅう|しょく|の|じ|かん","lunch time"
"kanken-9","昼ごはんを食べる","ひる|ごはん|を|た|べる","eat lunch"
"kanken-9","長方形","ちょう|ほう|けい","rectangle"
"kanken-9","校長先生","こう|ちょう|せん|せい","principal"
"kanken-9","長ぐつ","なが|ぐつ","boots"
"kanken-9","かみの毛が長い","かみ|の|け|が|なが|い","long hair"
"kanken-9","白鳥","はく|ちょう","swan"
"kanken-9","親鳥","おや|どり","parent bird"
"kanken-9","鳥小屋","とり|ご|や","aviary"
"kanken-9","野鳥をかんさつする","や|ちょう|を|かん|さつ|する","observe birds"
"kanken-9","朝刊","ちょう|かん","morning paper"
"kanken-9","朝食","ちょう|しょく","breakfast"
"kanken-9","朝日","あさ|ひ","morning sun"
"kanken-9","朝ごはんを食べる","あさ|ごはん|を|た|べる","eat breakfast"
"kanken-9","直線","ちょく|せん","line"
"kanken-9","正直な人","しょう|じき|な|ひと","honest person"
"kanken-9","こわれたおもちゃを直す","こわれた|おもちゃ|を|なお|す","fix toy"
"kanken-9","通学路","つう|がく|ろ","school route"
"kanken-9","通夜","つ|や","wake"
"kanken-9","大通り","おお|どお|り","main st"
"kanken-9","学校に通う","がっ|こう|に|かよ|う","go to school"
"kanken-9","子弟","し|てい","children"
"kanken-9","兄弟","きょう|だい","siblings"
"kanken-9","弟子","で|し","disciple"
"kanken-9","弟は電車がすきだ","おとうと|は|でん|しゃ|が|すき|だ","brother likes train"
"kanken-9","店員","てん|いん","clerk"
"kanken-9","商店","しょう|てん","shop"
"kanken-9","夜店","よ|みせ","night stall"
"kanken-9","新しい店ができる","あたら|しい|みせ|が|できる","new shop"
"kanken-9","終点","しゅう|てん","end point"
"kanken-9","百点","ひゃく|てん","100 pts"
"kanken-9","点線","てん|せん","dotted line"
"kanken-9","同点で引き分ける","どう|てん|で|ひき|わける","draw"
"kanken-9","電車","でん|しゃ","train"
"kanken-9","電話","でん|わ","phone"
"kanken-9","発電","はつ|でん","power gen"
"kanken-9","電池を入れかえる","でん|ち|を|いれ|かえる","change battery"
"kanken-9","木刀","ぼく|とう","wooden sword"
"kanken-9","ちょうこく刀","ちょうこく|とう","carving knife"
"kanken-9","古い刀を見せてもらう","ふる|い|かたな|を|みせてもらう","see old sword"
"kanken-9","冬季オリンピック","とう|き|おりんぴっく","winter olympics"
"kanken-9","冬休み","ふゆ|やす|み","winter break"
"kanken-9","さむい冬がやってくる","さむ|い|ふゆ|が|やってくる","cold winter"
"kanken-9","当番","とう|ばん","duty"
"kanken-9","弁当","べん|とう","bento"
"kanken-9","大当たり","おお|あ|たり","jackpot"
"kanken-9","まとにボールを当てる","まと|に|ぼーる|を|あ|てる","hit target"
"kanken-9","東京","とう|きょう","Tokyo"
"kanken-9","東の空","ひがし|の|そら","east sky"
"kanken-9","東の方へ歩いて行く","ひがし|の|ほう|へ|あるいて|い|く","go east"
"kanken-9","答案用紙","とう|あん|よう|し","answer sheet"
"kanken-9","返答","へん|とう","reply"
"kanken-9","しつもんに答える","しつもん|に|こた|える","answer q"
"kanken-9","頭上","ず|じょう","overhead"
"kanken-9","音頭","おん|ど","lead"
"kanken-9","頭がいたい","あたま|が|いた|い","headache"
"kanken-9","頭文字","かしら|も|じ","initial"
"kanken-9","マラソンで先頭を走る","まらそん|で|せん|とう|を|はしる","lead marathon"
"kanken-9","同数","どう|すう","same number"
"kanken-9","同時","どう|じ","same time"
"kanken-9","同じ色のくつを買う","おな|じ|いろ|の|くつ|を|か|う","same color shoes"
"kanken-9","道具","どう|ぐ","tool"
"kanken-9","水道","すい|どう","water"
"kanken-9","神道","しん|とう","shinto"
"kanken-9","坂道","さか|みち","slope"
"kanken-9","山の中で道にまよう","やま|の|なか|で|みち|に|まよう","lost in mt"
"kanken-9","読書","どく|しょ","reading"
"kanken-9","音読","おん|どく","aloud"
"kanken-9","本を読む","ほん|を|よ|む","read book"
"kanken-9","絵本をかりて読む","え|ほん|を|かりて|よ|む","borrow book"
"kanken-9","国内","こく|ない","domestic"
"kanken-9","内裏びな","だい|り|びな","dolls"
"kanken-9","内がわ","うち|がわ","inside"
"kanken-9","内と外","うち|と|そと","in and out"
"kanken-9","店内を歩き回る","てん|ない|を|ある|き|まわ|る","walk in shop"
"kanken-9","南極","なん|きょく","south pole"
"kanken-9","南国","なん|ごく","southern land"
"kanken-9","南がわのまどをあける","みなみ|がわ|の|まど|を|あける","open south window"
"kanken-9","牛肉","ぎゅう|にく","beef"
"kanken-9","肉体","にく|たい","body"
"kanken-9","市場で肉を買う","いち|ば|で|にく|を|か|う","buy meat"
"kanken-9","馬車","ば|しゃ","carriage"
"kanken-9","乗馬","じょう|ば","riding"
"kanken-9","竹馬","たけ|うま","stilts"
"kanken-9","絵馬","え|ま","votive"
"kanken-9","馬の絵をかく","うま|の|え|を|か|く","draw horse"
"kanken-9","売店","ばい|てん","kiosk"
"kanken-9","商売","しょう|ばい","business"
"kanken-9","売り場","う|り|ば","sales area"
"kanken-9","おいしいパンを売る","おいしい|ぱん|を|う|る","sell bread"
"kanken-9","売買","ばい|ばい","trade"
"kanken-9","買い物","か|い|もの","shopping"
"kanken-9","買い物かご","か|い|もの|かご","basket"
"kanken-9","マフラーを買う","まふらー|を|か|う","buy scarf"
"kanken-9","麦芽","ばく|が","malt"
"kanken-9","麦茶","むぎ|ちゃ","barley tea"
"kanken-9","麦わらぼうし","むぎ|わら|ぼうし","straw hat"
"kanken-9","米に麦をまぜて食べる","こめ|に|むぎ|を|まぜて|たべる","rice barley"
"kanken-9","半ズボン","はん|ずぼん","shorts"
"kanken-9","半分","はん|ぶん","half"
"kanken-9","試合半ばに雨がふる","しあい|なか|ば|に|あめ|が|ふる","rain mid game"
"kanken-9","番組","ばん|ぐみ","program"
"kanken-9","一番星","いち|ばん|ぼし","first star"
"kanken-9","日曜日には弟とるす番だ","にち|よう|び|に|は|おとうと|と|るす|ばん|だ","house sitting"
"kanken-9","父母","ふ|ぼ","parents"
"kanken-9","父の日","ちち|の|ひ","father's day"
"kanken-9","お父さん","お|とう|さん","dad"
"kanken-9","教会で神父の話を聞く","きょう|かい|で|しん|ぷ|の|はなし|を|き|く","priest"
"kanken-9","風船","ふう|せん","balloon"
"kanken-9","台風","たい|ふう","typhoon"
"kanken-9","風情","ふ|ぜい","taste"
"kanken-9","気もちのよい風がふく","きもち|の|よい|かぜ|が|ふく","nice wind"
"kanken-9","気分","き|ぶん","mood"
"kanken-9","二つに分ける","ふた|つ|に|わ|ける","divide"
"kanken-9","分かれ道","わか|れ|みち","fork"
"kanken-9","自分の顔の絵をかく","じ|ぶん|の|かお|の|え|を|か|く","draw self"
"kanken-9","新聞","しん|ぶん","newspaper"
"kanken-9","前代未聞","ぜん|だい|み|もん","unheard of"
"kanken-9","人の話を聞く","ひと|の|はなし|を|き|く","listen"
"kanken-9","なみの音が聞こえる","なみ|の|おと|が|きこ|える","hear waves"
"kanken-9","新米","しん|まい","new rice"
"kanken-9","米作","べい|さく","rice farming"
"kanken-9","秋にとれた米をおくる","あき|に|とれた|こめ|を|おくる","send rice"
"kanken-9","歩道","ほ|どう","sidewalk"
"kanken-9","散歩","さん|ぽ","walk"
"kanken-9","一歩すすむ","いっ|ぽ|すすむ","step"
"kanken-9","歩合","ぶ|あい","commission"
"kanken-9","池のまわりを歩く","いけ|の|まわり|を|ある|く","walk pond"
"kanken-9","母校","ぼ|こう","alma mater"
"kanken-9","母の日","はは|の|ひ","mother's day"
"kanken-9","お母さん","お|かあ|さん","mom"
"kanken-9","母と買い物に行く","はは|と|か|い|もの|に|い|く","shop with mom"
"kanken-9","方角","ほう|がく","direction"
"kanken-9","正方形","せい|ほう|けい","square"
"kanken-9","夕方","ゆう|がた","evening"
"kanken-9","先生の書き方をまねる","せん|せい|の|か|き|かた|を|まねる","imitate"
"kanken-9","北海道","ほっ|かい|どう","Hokkaido"
"kanken-9","北風","きた|かぜ","north wind"
"kanken-9","風船が北の方へとんでいく","ふう|せん|が|きた|の|ほう|へ|とんで|い|く","balloon north"
"kanken-9","毎日","まい|にち","every day"
"kanken-9","毎朝","まい|あさ","every morning"
"kanken-9","毎月かべ新聞を作る","まい|つき|かべ|しん|ぶん|を|つく|る","monthly paper"
"kanken-9","毎朝八時におきる","まい|あさ|はち|じ|に|おきる","wake 8am"
"kanken-9","姉妹","し|まい","sisters"
"kanken-9","妹","いもうと","sister"
"kanken-9","ぼくには妹と弟がいる","ぼく|に|は|いもうと|と|おとうと|が|いる","have siblings"
"kanken-9","万年筆","まん|ねん|ひつ","pen"
"kanken-9","万全","ばん|ぜん","perfect"
"kanken-9","広場に五万人があつまる","ひろ|ば|に|ご|まん|にん|が|あつまる","50000 people"
"kanken-9","発明","はつ|めい","invention"
"kanken-9","夜明け","よ|あ|け","dawn"
"kanken-9","明るい空","あか|るい|そら","bright sky"
"kanken-9","明日は遠足です","あした|は|えん|そく|です","tomorrow trip"
"kanken-9","悲鳴","ひ|めい","scream"
"kanken-9","共鳴","きょう|めい","resonance"
"kanken-9","鳥の鳴き声","とり|の|な|き|ごえ","chirp"
"kanken-9","サイレンを鳴らす","さいれん|を|な|らす","siren"
"kanken-9","毛布","もう|ふ","blanket"
"kanken-9","毛糸","け|いと","yarn"
"kanken-9","かみの毛","かみ|の|け","hair"
"kanken-9","庭で毛虫を見つける","にわ|で|け|むし|を|みつける","caterpillar"
"kanken-9","校門","こう|もん","gate"
"kanken-9","正門","せい|もん","main gate"
"kanken-9","門松","かど|まつ","kadomatsu"
"kanken-9","門の前でまち合わせる","もん|の|まえ|で|まち|あわせる","meet at gate"
"kanken-9","夜景","や|けい","night view"
"kanken-9","夜空","よ|ぞら","night sky"
"kanken-9","父は夜おそく帰ってくる","ちち|は|よる|おそく|かえってくる","dad late"
"kanken-9","野鳥","や|ちょう","wild bird"
"kanken-9","野原","の|はら","field"
"kanken-9","はたけで野菜をそだてる","はたけ|で|や|さい|を|そだてる","grow veg"
"kanken-9","友情","ゆう|じょう","friendship"
"kanken-9","親友","しん|ゆう","best friend"
"kanken-9","友だちとけんかをする","とも|だち|と|けんか|を|する","fight friend"
"kanken-9","用意","よう|い","prep"
"kanken-9","画用紙","が|よう|し","drawing paper"
"kanken-9","ペンを用いて字を書く","ぺん|を|もち|いて|じ|を|か|く","write with pen"
"kanken-9","一週間の曜日","いっ|しゅう|かん|の|よう|び","days of week"
"kanken-9","日曜日","にち|よう|び","Sunday"
"kanken-9","月曜日にテストがある","げつ|よう|び|に|てすと|が|ある","Monday test"
"kanken-9","未来","み|らい","future"
"kanken-9","春が来る","はる|が|く|る","spring comes"
"kanken-9","来るべき大会","きた|る|べき|たい|かい","upcoming"
"kanken-9","いとこがあそびに来る","いとこ|が|あそび|に|く|る","cousin comes"
"kanken-9","里帰り","さと|がえ|り","homecoming"
"kanken-9","千里眼","せん|り|がん","clairvoyance"
"kanken-9","母のふる里は遠い","はは|の|ふる|さと|は|とお|い","mom hometown"
"kanken-9","料理","りょう|り","cooking"
"kanken-9","理由","り|ゆう","reason"
"kanken-9","たんすの中を整理する","たんす|の|なか|を|せい|り|する","organize"
"kanken-9","会話","かい|わ","convo"
"kanken-9","むかし話","むかし|ばなし","folktale"
"kanken-9","楽しかったことを話す","たの|しかった|こと|を|はな|す","talk fun"`;
