// --- MAPPINGS ---

const POS_LABEL_MAP = {
  動詞: "Verb",
  助動詞: "Auxiliary Verb",
  助詞: "Particle",
  名詞: "Noun",
  形容詞: "Adjective",
  副詞: "Adverb",
  形状詞: "Adjectival Noun",
  代名詞: "Pronoun",
  接尾辞: "Suffix",
};

const JMDICT_TAG_MAP = {
  "adj-i": "adjective (keiyoushi)",
  "adj-na": "adjectival nouns or quasi-adjectives (keiyodoshi)",
  "adj-no": "nouns which may take the genitive case particle 'no'",
  "adj-pn": "pre-noun adjectival (rentaishi)",
  "adj-t": "'taru' adjective",
  "adj-f": "noun or verb acting prenominally",
  adj: "former adjective classification",
  adv: "adverb (fukushi)",
  "adv-n": "adverbial noun",
  "adv-to": "adverb taking the 'to' particle",
  aux: "auxiliary",
  "aux-v": "auxiliary verb",
  "aux-adj": "auxiliary adjective",
  conj: "conjunction",
  ctr: "counter",
  exp: "Expressions",
  int: "interjection (kandoushi)",
  iv: "irregular verb",
  n: "noun (common) (futsuumeishi)",
  "n-adv": "adverbial noun (fukushitekimeishi)",
  "n-pref": "noun, used as a prefix",
  "n-suf": "noun, used as a suffix",
  "n-t": "noun (temporal) (jisoumeishi)",
  num: "numeric",
  pn: "pronoun",
  pref: "prefix",
  prt: "particle",
  suf: "suffix",
  v1: "Ichidan verb",
  "v2a-s": "Nidan verb with 'u' ending (archaic)",
  v4h: "Yodan verb with 'hu/fu' ending (archaic)",
  v4r: "Yodan verb with 'ru' ending (archaic)",
  v5: "Godan verb",
  v5aru: "Godan verb - -aru special class",
  v5b: "Godan verb with 'bu' ending",
  v5g: "Godan verb with 'gu' ending",
  v5k: "Godan verb with 'ku' ending",
  "v5k-s": "Godan verb - iku/yuku special class",
  v5m: "Godan verb with 'mu' ending",
  v5n: "Godan verb with 'nu' ending",
  v5r: "Godan verb with 'ru' ending",
  "v5r-i": "Godan verb with 'ru' ending (irregular verb)",
  v5s: "Godan verb with 'su' ending",
  v5t: "Godan verb with 'tsu' ending",
  v5u: "Godan verb with 'u' ending",
  "v5u-s": "Godan verb with 'u' ending (special class)",
  v5uru: "Godan verb - uru old class verb",
  v5z: "Godan verb with 'zu' ending",
  vz: "Ichidan verb - zuru verb",
  vi: "intransitive verb",
  vk: "kuru verb - special class",
  vn: "irregular nu verb",
  vs: "noun or participle which takes the aux. verb suru",
  "vs-c": "su verb - precursor to the modern suru",
  "vs-i": "suru verb - irregular",
  "vs-s": "suru verb - special class",
  vt: "transitive verb",
};

const JMDICT_POS_MAP = {
  動詞: [
    "v1",
    "v1-s",
    "v2a-s",
    "v2b-k",
    "v2b-s",
    "v2d-k",
    "v2d-s",
    "v2g-k",
    "v2g-s",
    "v2h-k",
    "v2h-s",
    "v2k-k",
    "v2k-s",
    "v2m-k",
    "v2m-s",
    "v2n-s",
    "v2r-k",
    "v2r-s",
    "v2s-s",
    "v2t-k",
    "v2t-s",
    "v2w-s",
    "v2y-k",
    "v2y-s",
    "v2z-s",
    "v4b",
    "v4g",
    "v4h",
    "v4k",
    "v4m",
    "v4n",
    "v4r",
    "v4s",
    "v4t",
    "v5aru",
    "v5b",
    "v5g",
    "v5k",
    "v5k-s",
    "v5m",
    "v5n",
    "v5r",
    "v5r-i",
    "v5s",
    "v5t",
    "v5u",
    "v5u-s",
    "v5uru",
    "vi",
    "vk",
    "vn",
    "vr",
    "vs",
    "vs-c",
    "vs-i",
    "vs-s",
    "vt",
    "vz",
    "v-unspec",
  ],
  助動詞: ["aux", "aux-v", "aux-adj"],
  助詞: ["prt", "adv-to", "conj"],
  名詞: [
    "n",
    "n-adv",
    "n-pr",
    "n-pref",
    "n-suf",
    "n-t",
    "num",
    "ctr",
    "adj-no",
    "adj-pn",
    "pn",
    "suf",
    "pref",
    "vs",
    "exp",
  ],
  形容詞: ["adj-i", "adj-ix", "adj-kari", "adj-ku", "adj-shiku"],
  副詞: ["adv", "adv-to", "n-adv"],
  形状詞: ["adj-na", "adj-nari", "adj-no", "adj-f", "adj-pn", "n"],
  代名詞: ["pn"],
  接尾辞: ["suf", "n-suf", "c-suf", "v-suf"],
};

export { POS_LABEL_MAP, JMDICT_POS_MAP, JMDICT_TAG_MAP };
